### ISSUE TITLE
22:52:19] Starting download of updated addon files for Legion... [22:52:19] Downloading NerdPack... [22:52:45] Reference 'refs/remotes/origin/Legion' not found

### ISSUE THREAD

**Issue by caaol2008** [MrTheSoulz/NerdPack#10]
22:52:19] Starting download of updated addon files for Legion...
[22:52:19] Downloading NerdPack...
[22:52:45] Reference 'refs/remotes/origin/Legion' not found

**Comment by MrTheSoulz** [comment]
Legion branch has been merge to master and therefore no longer exists.
Download from master
