### ISSUE TITLE
@libs not being called anymore

### ISSUE THREAD

**Issue by modhunter** [MrTheSoulz/NerdPack#125]
This may be related to https://github.com/MrTheSoulz/NerdPack/issues/124

Something changed *after* 512ab1b which results in `@lib` calls not being executed anymore.

For example:

`{ "Crackling Jade Lightning", "@NOC.hitcombo(Crackling Jade Lightning)"},` no longer even enters the @NOC.hitcombo check.  Going back to commit 512ab1b and this works as expected.

**Comment by MrTheSoulz** [comment]
fixed
