### ISSUE TITLE
Req: Extended Roster

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#129]
As healer i need more information on the roster units
- Group : Which party it belings to(Healing Assignments 1-4)
- Position and or coordinates (x,y,z) if i am using a advanced unlocker i would like to have the coordinates for range checks etc
- Threat: Threat status so i know who have current aggro

**Comment by MrTheSoulz** [comment]
Position and or coordinates wont be added, they require advanced APIs,
the core only contains stuff that can be used with anything, will see about the other 2.

**Comment by Rabalaba** [comment]
Wouldn't threat be in relation to a Unitid such as target or mouseover?
