### ISSUE TITLE
Healing: Unit issues in halls of valor and dispel all does not work

### ISSUE THREAD

**Issue by tw88** [MrTheSoulz/NerdPack#130]
Healing in halls of valor fails if the group gets split by the "portals" to the forest for example. If 'lowest' is not in the same area as you, whole CR stops with a LUA Error. Maybe its about a failing distance check?

If i can test it again ill provide the error log.

2nd Issue i found is that the dispel action gets stuck in a deadlock where it tries to cast the spell XX amount of times at the same target - locking the whole CR unitl the debuff has gone.

**Comment by MrTheSoulz** [comment]
"whole CR stops with a LUA Error"
Can you sent the lua error?

Working on the dispel issue.

**Comment by tw88** [comment]
I think this is it:

Error occured in: Global
Count: 1
Message: ..\AddOns\NerdPack\system\healing.lua line 31:
   Usage: UnitHealth("unit")
Debug:
   [C]: ?
   [C]: ?
   NerdPack\system\healing.lua:31: Add()
   NerdPack\system\healing.lua:62: Garbage()
   NerdPack\system\healing.lua:21: GetRoster()
   NerdPack\fakeunits.lua:14:
      NerdPack\fakeunits.lua:12
   (tail call): ?
   NerdPack\system\parser.lua:52: Target()
   NerdPack\system\parser.lua:89: Parse()
   NerdPack\system\parser.lua:77:
      NerdPack\system\parser.lua:74
   (tail call): ?
   NerdPack\system\parser.lua:123:
      NerdPack\system\parser.lua:116
   ..\SharedXML\C_TimerAugment.lua:16:
      ..\SharedXML\C_TimerAugment.lua:14

**Comment by MrTheSoulz** [comment]
fixed
