### ISSUE TITLE
leverage nameplates to count # of enemies for generic unlockers

### ISSUE THREAD

**Issue by modhunter** [MrTheSoulz/NerdPack#131]
While it appears that we cannot act on `nameplate[1-20]` anymore, we should still have the ability to 'count' the number of enemies using the nameplates stuff which is useful for generic unlockers to know the number of nearby enemies for AOE purposes.

I think there is value in figuring out how to incorporate this into NerdPack.

Creating this issue to track progress on this endeavor.

**Comment by MrTheSoulz** [comment]
i dont think we can do this, at leats not with the current design of the OM.
The om gets units from everywhere it can so for example, if party1 is added it may be nameplateX and since we dont have the GUID of nameplateX we dont know if they'r the same unit so it would count 2 instead of just 1.
Theres also the part where we have to create a hack to sum the objects and the plates.

Overwall i dont think its worth it, unfortunately.

**Comment by modhunter** [comment]
The Addon 'Enemygrid' can show a list of friendly or enemy or neutral units around the player.  Now in 7.1 it still operates the same way but you are not able to interact with the units via the addon, but it still knows about them (it even show debuffs) just as before.

**Comment by MrTheSoulz** [comment]
Can we still get the GUID? if so this could work.

**Comment by modhunter** [comment]
I think it is possible:

```
local version = GetBuildInfo()
--if not version:find('^7.0') then return end

local lnr = LibStub("AceAddon-3.0"):NewAddon(n_name, "LibNameplateRegistry-1.0")

function lnr:OnEnable()
	self:LNR_RegisterCallback("LNR_ON_NEW_PLATE")
	self:LNR_RegisterCallback("LNR_ON_RECYCLE_PLATE")
end

function lnr:LNR_ON_NEW_PLATE(_, _, plateData)
	print("new plate: "..plateData.name.." ("..plateData.GUID..")");
	NeP.OM:Add(plateData.unitToken)
end
```


And in-game:

```
new plate: Dungeoneer's Training Dummy (Creature-0-3882-1514-23182-92168-00008FEF9E)
new plate: Dungeoneer's Training Dummy (Creature-0-3882-1514-23182-92168-00000FEF9E)
new plate: Dungeoneer's Training Bag (Creature-0-3882-1514-23182-100441-00008FEF9E)
new plate: Dungeoneer's Training Bag (Creature-0-3882-1514-23182-100441-00028FEF9E)
new plate: Raider's Training Bag (Creature-0-3882-1514-23182-100451-00028FEF9E)
new plate: Raider's Training Bag (Creature-0-3882-1514-23182-100451-00010FEF9E)
```

**Comment by MrTheSoulz** [comment]
Ok cool, i can hack something up then

**Comment by jrubimf** [comment]
Well old OM was working fine for counting mobs.

**Comment by MrTheSoulz** [comment]
@jrubimf these are things we know :P
what needs to be done is seperating the counting from the OM since these units CANNOT be inserted in the same place as valid ones.
i already started work, the OM returns both units a count, now i need to tweak it a bit futher to fit it all.

**Comment by modhunter** [comment]
I think the excellent way in which @MrTheSoulz has had things so modular that a change like this is even possible!

**Comment by heistcode** [comment]
Oh this is good info for when I want to expand TargetLock's features. https://github.com/heistcode/NerdPack-TargetLock/issues/1

**Comment by heistcode** [comment]
Good info for when I want to expand TargetLock's features. https://github.com/heistcode/NerdPack-TargetLock/issues/1

**Comment by MrTheSoulz** [comment]
This should be fixed now, closing.
