### ISSUE TITLE
WoW crash while using EWT

### ISSUE THREAD

**Issue by buginote** [MrTheSoulz/NerdPack#134]
NerdPack current master version with EWT got crash after changing region(eg. in/out Dungeons or Arena).
A temp solution is "/reload ui" command after changing region every time.

**Comment by MrTheSoulz** [comment]
Does this still happen?

**Comment by buginote** [comment]
Still happen. 
eg. teleport from raid/dungeon by portal

**Comment by MrTheSoulz** [comment]
Did you get a crash report file near ewt?
if so sent it please.

**Comment by buginote** [comment]
After update to EWT3273 today, works well, no crash untill now
