### ISSUE TITLE
Lua error in om.lua / healing.lua

### ISSUE THREAD

**Issue by Biibou** [MrTheSoulz/NerdPack#136]
Im getting this error sometimes, rotation continue to execute correctly (Im not a healer though) :

```
2x [string "C:\ToolZ\FH\Lua\Object.lua"]:18: The GUID does not belong to an existing object.
[C]: in function `ObjectPosition'
[string "C:\ToolZ\FH\Lua\Object.lua"]:18: in function <[string "C:\ToolZ\FH\Lua\Object.lua"]:16>
(tail call): ?
NerdPack\system\om.lua:37: in function `Get'
NerdPack\system\healing.lua:65: in function <NerdPack\system\healing.lua:64>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
```

There is a check for UnitExists(Obj.key) but it isn't enough, it seems not to like elseif/else.

Also, I don't know if it's related to the ObjectManager but since you change how it works a few time ago, my WoW randomly crash (error 132) when entering combat. 
~2 crash on a 6 hours session (World Quest/Daily heroic dunjeon etc...).

**Comment by MrTheSoulz** [comment]
this should be fixed now, closing
