### ISSUE TITLE
UnitGetIncomingHeals

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#137]
In healing engine we are using UnitGetIncomingHeals to get predicted health.
This function is currently bugged and is giving wrong values.

We should look at unit frame addons that is showing incoming heals, such as Elvui.

**Comment by macedoniazxv** [comment]
+

**Comment by heistcode** [comment]
ElvUI and oUF are using UnitGetIncomingHeals.

https://github.com/oUF-wow/oUF/blob/master/elements/healprediction.lua#L81
http://git.tukui.org/Elv/elvui/blob/master/ElvUI/Libraries/oUF/elements/healprediction.lua#L83
