### ISSUE TITLE
Frost Death Knight Combot routines doesn't work after killing one mob.

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#138]
@MrTheSoulz 
Good Day Sir.
I updated Combat Routines with NerdPack ToolBox today, then Combat Routines doesn't work when My toon switches from Specialization Blood to Specialization Frost.
Unfortunately,I did not back up the files of last version.
![qq20161102232754](https://cloud.githubusercontent.com/assets/8578753/19935392/dd65c03c-a154-11e6-9f8f-94817fb30a19.png)

**Comment by MrTheSoulz** [comment]
Look like a CR issue, contact the author.
