### ISSUE TITLE
Elemental cooldowns

### ISSUE THREAD

**Issue by Tonppa3d** [MrTheSoulz/NerdPack#14]
Elemental shaman is using all cooldowns when they're ready (ascendance, elemental totems etc...). This can lead to unwanted situations when you need to delay your cooldowns in heroic/mythic bosses. Would like to have some control when they're used.

**Comment by MrTheSoulz** [comment]
The problem with this is how would one predict when to use it?
on hero? on target is boss? on low health? what about if the user want to force it?
That would require alot of duplicated code.

That being said how would you want it to predict? i could add some situations.

**Comment by Tonppa3d** [comment]
Maybe in same way it's done in TeamPhoenix routine? You just push the use cooldowns button (which is inbuilt in PE?). That way you can at least control when you use your cooldowns.

**Comment by MrTheSoulz** [comment]
Thanks, it should be doing exactly that, for some reason the nest wasn't conditioned...
Ive sent a fix for it :)

**Comment by MrTheSoulz** [comment]
Closing this bug now, please re-open if it theres anymore issues with Shaman-Ele cooldowns.
