### ISSUE TITLE
CR doesn't execute on Mind Controlled players on Mythic Nythendra

### ISSUE THREAD

**Issue by heistcode** [MrTheSoulz/NerdPack#142]
CR doesn't execute on Mind Controlled players on Mythic Nythendra.

**Comment by modhunter** [comment]
FWIW, this is also logged in https://github.com/MrTheSoulz/NerdPack-CombatHelper/issues/2

**Comment by modhunter** [comment]
https://github.com/MrTheSoulz/NerdPack-CombatHelper/pull/8 should fix this
