### ISSUE TITLE
Target replacing

### ISSUE THREAD

**Issue by macedoniazxv** [MrTheSoulz/NerdPack#149]
simple 
{'Spell', nil, 'lowest'}, --cast spell in 'player'. With any condition to.

**Comment by MrTheSoulz** [comment]
Sent updates for this, let me know if its fixed.

**Comment by macedoniazxv** [comment]
not fixed

**Comment by MrTheSoulz** [comment]
Moust people reporting this have confirmed the fix, please provide more details.

**Comment by macedoniazxv** [comment]
Last update nep(delete old folder to be sure). Cast only in 'player'. But if i have 'target'  - nep try to cast in main target:
https://i.gyazo.com/b6cf31b648988f1c6cdf8e6a11f1afe0.png
Player 'Brookz' is enemy.

**Comment by heistcode** [comment]
Are you using the TargetLock plugin? I don't see how that would effect this but thought we ought to eliminate it since it does mess with fakeunits.

**Comment by macedoniazxv** [comment]
Only nep+protect

**Comment by ricochico** [comment]
can confirm! using stock rotation holypriest it keeps spamming renew while moving, even when the buff is up. u could just remove player from lowest as u almost certainly got other conditions for it in the rotation.
