### ISSUE TITLE
cursor.ground not working as intended

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#150]
Latest NeP and Protected using FH
casts at selected target or if none it casts on player but never at cursor location

**Comment by Yobleed** [comment]
and :

 if a spell has been cast with a .ground condition the cursor resets. is it possible to fix this? it's kinda hard when pressing Right-Click to steer ur character
For example. 
    {'Angelic Feather', 'player.movingfor >= 2 & !player.buff(Angelic Feather) & spell(Angelic Feather).charges >= 1 & UI(m_AF)', 'player.ground'}
 if cast it resets my cursor so it's like I'm not holding right-click anymore
I'm using Firehack btw
not sure if it's an advanced unlocker issue

**Comment by Yobleed** [comment]
used to work on old NeP

**Comment by heistcode** [comment]
Try
{'/cast [@player] Angelic Feather', 'whateverconditions'},

**Comment by heistcode** [comment]
Or
{'/cast [@cursor] Angelic Feather', 'blah'}

**Comment by heistcode** [comment]
I'm of the mind that we ought to be using these new macro conditionals for those two cases.

**Comment by MrTheSoulz** [comment]
@yobleed, resets the cursor?? To the center of the screen? Advanced right

**Comment by Yobleed** [comment]
@MrTheSoulz  no I just releases the cursor not reset.. :P Like if you would press Right-Click it would release it
