### ISSUE TITLE
Mysterious healing.lua bug

### ISSUE THREAD

**Issue by heistcode** [MrTheSoulz/NerdPack#155]
In certain situations /dump NeP.DSL:Get("health")("player") will return odd results. I get it most frequently after raid so it might be connected to leaving a group or changing zones but I've also had it in other situations. I just got it after raid and remembered not to reload my UI right away.

/dump NeP.DSL:Get("health")("player")
[1]=-1.#IND
/dump NeP.DSL:Get("health.actual")("player")
[1]=0
/dump math.floor((UnitHealth("player") / UnitHealthMax("player")) * 100)
[1]=100
The object manager GUI shows me as 100 health.

**Comment by heistcode** [comment]
/dump UnitGetIncomingHeals("player")
[1]=0
/dump UnitGetTotalHealAbsorbs("player")
[1]=0

**Comment by heistcode** [comment]
/dump NeP.DSL:Get("health.max")("player")
[1]=*my actual max HP*

**Comment by heistcode** [comment]
OK. Doing /dump NeP.OM.GetRoster() fixes the issue.
/dump NeP.DSL:Get("health")("player")
[1]=100

**Comment by MrTheSoulz** [comment]
Ohhh

**Comment by MrTheSoulz** [comment]
Ohh, health is beinh update when you call roster...
