### ISSUE TITLE
Lifebloom not casting

### ISSUE THREAD

**Issue by Lyaruil** [MrTheSoulz/NerdPack#157]
On Resto Druid, Lifebloom spell will not cast. 

My condition is as follows:

{ "Lifebloom", { 
    "tank.health <= 50", 
    "tank.buff(Lifebloom)", 
    "tank.range <= 40",
  }, "tank" },

Is this a bug or am I doing something wrong?

**Comment by NerdFan** [comment]
Do you want to rebuff or buff if buff is not found?
For 2nd option:
`"!tank.buff(Lifebloom)",`
