### ISSUE TITLE
I cant use an item 

### ISSUE THREAD

**Issue by ngmafia** [MrTheSoulz/NerdPack#159]
I try use one trinket but i cant...
my code is {'#Horn of valor', 'player.buff(Avatar) & player.buff(20572)'},

buffs is ok cuz i use in other lines and Works.

**Comment by modhunter** [comment]
Th is may be related to https://github.com/MrTheSoulz/NerdPack/issues/144

**Comment by NerdFan** [comment]
Is it "Horn of valor" or "Horn of Valor"?
Maybe this is reason of non-working item!

http://www.wowhead.com/item=133642/horn-of-valor&bonus=1826
