### ISSUE TITLE
NerdPack-1.7-r1  mouseover.ground error

### ISSUE THREAD

**Issue by emulcube** [MrTheSoulz/NerdPack#160]
NerdPack-1.7-r1 install
NerdPack-Protected install
Using FireHack

Routines code

{'Heroic Leap', 'keybind(lcontrol)' , 'cursor.ground'}

Execution

1x NerdPack-Protected\generic.lua:66: The object is invalid
[C]: ?
NerdPack-Protected\generic.lua:66: in function `?'
NerdPack\system\parser.lua:103: in function `Parse'
NerdPack\system\parser.lua:77: in function <NerdPack\system\parser.lua:74>
(tail call): ?
NerdPack\system\parser.lua:123: in function <NerdPack\system\parser.lua:116>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = nil

I need help

**Comment by MrTheSoulz** [comment]
Update to master branch, tgis is fixed there
