### ISSUE TITLE
 Question once again

### ISSUE THREAD

**Issue by emulcube** [MrTheSoulz/NerdPack#161]
NerdPack 1.8-beta2
NerdPack-Boxo_Routines
FireHack 2.3.7

in game /reload
Execution
{'Heroic Leap', 'keybind(lcontrol)' , 'cursor.ground'}

3x NerdPack-Protected\generic.lua:66: The object is invalid
[C]: ?
NerdPack-Protected\generic.lua:66: in function `?'
NerdPack\system\parser.lua:77: in function <NerdPack\system\parser.lua:71>
(tail call): ?
NerdPack\system\parser.lua:89: in function `Parse'
NerdPack\system\parser.lua:127: in function <NerdPack\system\parser.lua:120>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

**Comment by Yobleed** [comment]
Something wrong with cursor.ground. use '/cast [@cursor] spell' for now
