### ISSUE TITLE
Request for Global Actions

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#163]
If it is not against some policy you have in mind, please make Actions globally available so it is possible to add custom actions.

"Dirty" fix to add at the end of NerdPack/system/actions.lua:

```
-- Gobals
NeP.Globals.Actions = NeP.Actions
```

**Comment by MrTheSoulz** [comment]
Im not sure i want to allow this.
Is there a reason why you need it?
You should be able to do similar with libs
{"@mylib.myfunc"}
