### ISSUE TITLE
Actions and parsing target

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#164]
There are actions that sets target according some logic:
```
			eval.spell = spell
			eval.target = Obj.key
			eval.func = 'Cast'
```

Seems that this does not work because real action target will be always some default like "target" or "player".
It looks for me that this code part fails in NerdPack/system/parser.lua
function NeP.Parser.Target(eval):
```
	-- Target is returned from a function
	elseif eval[3].func then
		eval[3].target = eval[3].func()
	end
```
What function called after? 

"Dirty" fix that seems to work as expected:
```
	-- Target is returned from a function
   elseif eval.target then
      eval[3].target = eval.target
   elseif eval[3].func then
      eval[3].target = eval[3].func()
   end

```

**Comment by MrTheSoulz** [comment]
shoul.d be fixed by: https://github.com/MrTheSoulz/NerdPack/commit/986b4c1e7cc5f420655d2d8943710f0673307221
