### ISSUE TITLE
Checkspin

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#165]
Checkspin doesnt always work. while doing it seperatly with checkbox AND spinner it works flawlessly

**Comment by Yobleed** [comment]
"Trip - Today at 2:19 AM
Hm
I think my issue is with checkspin then
None of my checkspins seem to be working
Okay yeah, spinners are working, but checkspin isn't."

So its confirmed also by another player

**Comment by MrTheSoulz** [comment]
Should be fixed
