### ISSUE TITLE
Pet healing in lowest 

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#177]
Mr Cr is trying to heal pets when UNIT is lowest. Is it possible to change it to

**Comment by Yobleed** [comment]
Players only. Rabbs told me this could work : C_Timer.NewTicker(0.1, (function()
    -- Add refresh
    for GUID, Obj in pairs(NeP.OM:Get('Friendly')) do
        if  UnitInParty(Obj.key)
        or UnitIsUnit('player', Obj.key) then
            if Roster[GUID] then
                Refresh(GUID, Obj)
            elseif Obj.distance < maxDistance then
                Add(Obj)
            end
        end
    end
    -- Clean
    Clean()
end), nil)

**Comment by MrTheSoulz** [comment]
Will look at it, thanks.
