### ISSUE TITLE
Issues with generic unlock detection

### ISSUE THREAD

**Issue by modhunter** [MrTheSoulz/NerdPack#18]
I'll try to figure this out, but putting it here just in case for tracking:

Observing that sometimes the engine doesn't think it's unlocked unless I take the following steps:
1. toggle MasterToggle off
2. click 'Unlock!'
3. toggle MasterToggle on

**Comment by DarkNemie** [comment]
I unlock from the Char select screen  and have the same issue on first load, 
MasterToggle On should run first the same code as 'Unlock!' - Or should I say that is how PE did it.

**Comment by MrTheSoulz** [comment]
Should be fixed in the lastest protected module, thanks!
