### ISSUE TITLE
Healing CR stops 

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#180]
`[string "C:\Program Files\FireHack 2.3.7\Lua\Object...."]:18: The GUID does not belong to an existing object.
Count: 1

Call Stack:
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
[C]: in function `ObjectPosition'
[string "C:\Program Files\FireHack 2.3.7\Lua\Object...."]:18: in function <[string "C:\Program Files\FireHack 2.3.7\Lua\Object...."]:16>
(tail call): ?
Interface\AddOns\NerdPack\system\healing.lua:106: in function <Interface\AddOns\NerdPack\system\healing.lua:101>
(tail call): ?
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:123: in function <Interface\AddOns\NerdPack\system\dsl.lua:118>
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:58: in function <Interface\AddOns\NerdPack\system\dsl.lua:56>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:98: in function `Parse'
Interface\AddOns\NerdPack\system\parser.lua:89: in function `Parse'
Interface\AddOns\NerdPack\system\parser.lua:127: in function <Interface\AddOns\NerdPack\system\parser.lua:120>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>`

I'm not sure why it does it sometimes, 
also asked in FH discord 
and it should be a nerdpack issue. 

> l0l1dk - Today at 1:01 AM
Yes, it's an issue with NerdPack

**Comment by MrTheSoulz** [comment]
Please re-open this if the error happens again.
