### ISSUE TITLE
Broken Item Usage (Problem Found)

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#183]
Soulz,

Since recently potions are not being used when asked to.

1) ` Potion of Prolonged Power usage before pull if enabled in UI.
	{'#142117', 'pull_timer <= 3'},`
This is what it looks like in my CR. 
Problem was it doesn't do anything when the conditions are met.

2) I removed the conditions to see if there was something wrong with my condition writing. (`{'#142117'},`)
And it used the Item without a prob. Afterwards I tested it with a condition that would always be met like 
`{'#142117', 'player.buff(Shadowform)'},` AND THEN IT BROKE AGAIN?! (*insert Rage*)  NOW we go to 3 with some stupid question in it.

3) Could it be that Items don't allow Conditions anymore?

Sincerely,
Yobleed <3

**Comment by MrTheSoulz** [comment]
I havê my doubts conditions  are broken, try using a item when moving or something.

**Comment by Yobleed** [comment]
ok Soulz,

so I found out conditions aren't broken. but It takes too long for it to be used. There's a delay on the item usage so if a certain condition is met but if the delay is too long it won't use it. Might have something to do with the item usage blacklisting?

**Comment by MrTheSoulz** [comment]
the APIs for item usage are a mess atm, the delay is due to the blacklist, will look into tweaking it so it dosent take this long.
