### ISSUE TITLE
count separate debuffs w/ same name

### ISSUE THREAD

**Issue by aeonabyss** [MrTheSoulz/NerdPack#189]
For affliction, we need a way of counting the number of Unstable Afflictions that are on the target.
UA can be cast multiple times on the target, but they do not stack. They are individual debuffs.

hit me up and I can show you in gave via teamviewer.

**Comment by heistcode** [comment]
That's pretty easy to do. Do you just need to know how many there are or do you need timers for each?

**Comment by aeonabyss** [comment]
Just a count at this point.

**Comment by MrTheSoulz** [comment]
UNIT.debuff/buff(DEBUFF).many > #
