### ISSUE TITLE
Target stun condition

### ISSUE THREAD

**Issue by Orodriana** [MrTheSoulz/NerdPack#194]
Is it possible to check if a target is stunned? Something like target.state.stun, like it was in PE.
I tryed to make this:
{'215661', 'target.state.stun&player.holypower>=5&target.range<8'},
This is a retri pali's Justicar's Vengeance. Does not work. Works only if i check for Hummer of Justice debuff.

**Comment by MrTheSoulz** [comment]
try target.state(stun)

**Comment by Orodriana** [comment]
Nope, does not work.

**Comment by Orodriana** [comment]
Seems it work on enUS clients only, is it possible?

**Comment by Orodriana** [comment]
Does NeP check for english debuff names for "player.state(stun)"? If it so, where i can find those debuff names to edit it?

**Comment by MrTheSoulz** [comment]
@Orodriana https://github.com/MrTheSoulz/NerdPack/tree/master/locale, find the file that contains your language and translate from EnUS
