### ISSUE TITLE
issue with target.debuff

### ISSUE THREAD

**Issue by subzrk** [MrTheSoulz/NerdPack#195]
was using my assassination rogue roation and noticed that my rupture won't be applied if there another assassination rogue in the raid/party and rotation continues like if my debuff is applied , which isn't .
so target.debuff can't check if the debuff was mine or no .

**Comment by MrTheSoulz** [comment]
I've sent a commit that should fix this, closing.

PS: use ".any" to check if its applied by anyone including you.
