### ISSUE TITLE
Issues after todays patch (21.march.2017)

### ISSUE THREAD

**Issue by adde88** [MrTheSoulz/NerdPack#196]
Example: My hunter now keeps enabling/disabling volley, even if i use
```LUA
{'Volley', 'talent(6,3)&!player.buff(Volley)&toggle(xVolley)'},
```
That line above worked before the update that came today.

I also noticed that NerdPack keeps spamming my chat window with the spells that are being used.
I suspect this file "conditions/buffs.lua" line 29: is responsible.
```LUA
print(target, spell)
```

**Comment by subzrk** [comment]
yeah after updating now things missed up , 
first thing i noticed when the rotation was tried to make crippling poison , it keeps making it forever even i have the buff and types in chat player Crippling Poison , when i commented the code of it to check others , the next line was going in stealth , the code is {'Stealth', '!stealthed '} it print in chat all the stealth abilities , something went wrong for sure when trying to fix the buffs/debuffs

**Comment by MrTheSoulz** [comment]
Revert  to a previous commit for now, i messed up somewhere.

**Comment by adde88** [comment]
Everything is stable, thanks! :)
