### ISSUE TITLE
Instant dispel Fix

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#198]
> MrTheSoulz - Yesterday at 12:04 AM
> @Yobleed i think there was a random delay
> Yobleed - Yesterday at 9:35 AM
> @MrTheSoulz u sure? Cuz it did once dispell instantly...
> MrTheSoulz - Yesterday at 12:24 PM
> @Yobleed yep, your right
> Theres no delay at all
> Yobleed - Yesterday at 12:24 PM
> Ahaaa
> MrTheSoulz - Yesterday at 12:25 PM
> Will add it soon
> Yobleed - Yesterday at 12:25 PM
> Thx

**Comment by MrTheSoulz** [comment]
added, let me know how it works
