### ISSUE TITLE
Object Manager is behaving really weird

### ISSUE THREAD

**Issue by Chiisato** [MrTheSoulz/NerdPack#20]
Sometimes it doesn't add everyone or anyone to the friendly object list and it requires me to rezone/relog to sometimes fix it. In generally it feels very clunky

**Comment by MrTheSoulz** [comment]
Hello,
Please provide the unlocker details (FireHack; Genric).

Thanks, MTS.

**Comment by Chiisato** [comment]
I'm using firehack

**Comment by Chiisato** [comment]
Got some lua-errors

...AddOns\NerdPack\system\ObjectManager\ObjectCache.lua:273: attempt to call global 'UnitIsEnemie' (a nil value)

**Comment by MrTheSoulz** [comment]
I've confirmed and worked around that error.
it seems like UnitIsEnime API is unstable...
Sometimes it works, others, not so much.

Let me know if that fixed the issues you had.

**Comment by Chiisato** [comment]
I'll give it a spin in tonights raid and let you know how it works out, thanks!

**Comment by Chiisato** [comment]
Seems to have fixed the issue but I haven't tried it in more then LFG, I'll try it in LFR and some heroic/mythic tonight and see how it goes, I'll get back to you, thanks!

**Comment by MrTheSoulz** [comment]
Glad it got fixed, closing this error.
Re-open it acts up again :)
