### ISSUE TITLE
From some version,the "player.buff().count" doesnot work fine.

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#201]
{ '195182', 'player.buff(195181).count <= 6', 'target'}, this condition does not work fine .

**Comment by zy4944796** [comment]
the older version runs well :
NeP.DSL:Register("buff.count", function(target, spell)
	local buff,count,_,caster = UnitBuff(target, spell)
	if not not buff and (caster == 'player' or caster == 'pet') then
		return count
	end
	return 0
end)

But the lastest version func in buffer.lua doesn't work fine:

local function UnitBuffL(target, spell, own)
  local name,_,_,count,_,_,expires,caster = UnitBuff(target, spell, nil, own)
  return name, count, expires, caster
end

NeP.DSL:Register("buff.count", function(target, spell)
  local buff, count = UnitBuffL(target, spell, 'PLAYER')
  return buff and count or 0
end)

**Comment by MrTheSoulz** [comment]
is this issue still present?

**Comment by zy4944796** [comment]
@MrTheSoulz
 Good day sir,glad to see your reply.
Yes,it is still present, so I have to use the old edition which is 1.7 and didnot update after 11/3/2016.
However, the old one have a small problem in wow 7.2.
From wow version 7.2 ,the old Nerdpack caused the weapon button(icon) in the character information panel is gray, which means the icon is disabled,so artifact panel cannot be opened .
I have tryed my best to fix this bug,but there is too many code to fixed position the issue.

postscript:
my bot is NerdPack-DarkN-CR,and my character is blood dk.
 { '206930',{'player.buff(195181).count > 6', 'player.runes > 2'}, 'target'},

**Comment by MrTheSoulz** [comment]
That cr will not work on new versions of nep.
{ '206930',{'player.buff(195181).count > 6', 'player.runes > 2'}, 'target'},

Would look like:
{ '206930', 'player.buff(195181).count > 6 & player.runes > 2', 'target'},

**Comment by MrTheSoulz** [comment]
The issue with nep 1.7 and wow 7.2 can be fixed by updating libartifactdata to version 1.2
