### ISSUE TITLE
Opening / Clicking thigns while in combat

### ISSUE THREAD

**Issue by aeonabyss** [MrTheSoulz/NerdPack#202]
Keeps trying to attack targets while attempting to open/click world objects (quest things, chests, etc).

**Comment by MrTheSoulz** [comment]
is there a castbar when this happens?
im trying to find a way to track it with no luck...

**Comment by zy4944796** [comment]
I also found this issue.
this issue has only recently occurred.
from 7.2 may be.

**Comment by aeonabyss** [comment]
if there is a cast bar I can't see it because NEP is causing it to stop too quickly.

**Comment by adde88** [comment]
I also experience this.
If you're asking about a castbar that shows the progress of the interaction with the objects, it shows for me when i'm using the addon: Quartz
