### ISSUE TITLE
Request SendKey Action

### ISSUE THREAD

**Issue by Kleei** [MrTheSoulz/NerdPack#207]
I need to add space key action in rotation for Demon Hunter , before 0.3 seconds Fel Rush to be send space key , that way it will jump and do dmg/recover fury on the same position. I will add my rotations soon. Thanks.

**Comment by MrTheSoulz** [comment]
This would depend an advanced unlocker since wow dosent allow the usage of keys.
You could use JumpOrAscendStart() tho...

{"/run JumpOrAscendStart()"}

**Comment by Kleei** [comment]
Good tip but after all we can't detect that player is jumping

local FelRush = {
	{'&Fel Rush', 'condition'}, -- is jumping
	{'/run JumpOrAscendStart()'}, -- i don't get how to jump just for once not for >10 times.
}
local inCombat = {
      {FelRush, 'talent(1,1) & player.spell(Fel Rush).charges>=1 & target.enemy & target.alive & target.range<=5 & player.fury<=39'},

**Comment by MrTheSoulz** [comment]
try:
{'/run JumpOrAscendStart()', 'lastcast(Fel Rush)'},

Should only jump after casting fel rush

**Comment by MrTheSoulz** [comment]
Bug reported for EWT can be found here:
https://github.com/MrTheSoulz/NerdPack-Protected/issues/8

**Comment by Kleei** [comment]
> try:
{'/run JumpOrAscendStart()', 'lastcast(Fel Rush)'},
Should only jump after casting fel rush.
  Just tested.
That way combo is not working because when Fel Rush is in animation all other actions is suspended.
But if you jump and then use Fel Rush the character will stay on the same position.

**Comment by adde88** [comment]
I'm farily certain it's possible to write a function that does all of this stuff.
Register it with NeP.Library.Add, and then call it within the rotation with the conditions you want.

**Comment by Kleei** [comment]
I'm pretty sure it's possible to write a function but i'm afraid i don't have enough knowledge to write a function. Can someone help me with it ?

**Comment by MrTheSoulz** [comment]
Added:
{"%SendKey(KEY)", CONDITION}
