### ISSUE TITLE
I still use nerdPack 1.7,But  the weapon button in the character information panel is gray.

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#209]
@MrTheSoulz
I update the NerdPack and NerdPack Protected Module s to the latest version 1.8,but no combat routines can be selected.
![qq20170617114811](https://user-images.githubusercontent.com/8578753/27249939-917fddf4-5353-11e7-8006-6d471a6fac07.png)

 I roll back to nerdPack 1.7,But  the weapon button in the character information panel is gray.
![qq20170617115347](https://user-images.githubusercontent.com/8578753/27249942-bb36939a-5353-11e7-8f63-d49f00a57192.png)

**Comment by MrTheSoulz** [comment]
The new build (1.8) dosent include any CR's, make sure to download some.
Use the toolbox if you have issues installing it.

**Comment by zy4944796** [comment]
@MrTheSoulz 
Morning sir,
I found the function "buff.count" is not run on  non-English wow.

{'195182', 'player.buff(195181).count<=6&talent(3,1)&target.inFront&target.inMelee'},

**Comment by zy4944796** [comment]
@MrTheSoulz 
Does this version support spellid ?When I changed the spell id to spell name ,the 'buff.count' performed.

This code work fine:
{'Marrowrend', 'player.buff(Bone Shield).count<=6&talent(3,1)&target.inFront&target.inMelee'},
but the following examples not:
{'195182', 'player.buff(195181).count<=6&talent(3,1)&target.inFront&target.inMelee'},

**Comment by MrTheSoulz** [comment]
Please dont reported different issues inside the same one, makes it hard to track...

bug report for buff.count is here:
https://github.com/MrTheSoulz/NerdPack/issues/210
