### ISSUE TITLE
Disc priest rotation does not use clarity of will

### ISSUE THREAD

**Issue by Chiisato** [MrTheSoulz/NerdPack#21]
Does not use clarity of will on any targets, no matter what I set the setting to. Also feels like the disc rotation could get an overhaul in general

**Comment by MrTheSoulz** [comment]
Whats the reason for the overhaul?
Low HPS? Bad logic?

**Comment by MrTheSoulz** [comment]
Ive tested it and it dos cast, only fails to cast it on lowest beacuse of lowest.buff(#) not working correctly.

It casts fine on player/tank/focus.

Since this is a PE bug i cannot fix it.

**Comment by MrTheSoulz** [comment]
However i'm looking for a way to improve clarity of will for units that do work.
I need to find a way to stack it.

**Comment by Chiisato** [comment]
Yeah, clarity of will only casts on player/tank/focus, same with PW:Shield. Prayer of mending could use a interface option to set when to cast on tanks instead of a fixed value. I'm not sure if penance works correctly
