### ISSUE TITLE
buff.count doesnt like spellids

### ISSUE THREAD

**Issue by MrTheSoulz** [MrTheSoulz/NerdPack#210]
Opening this bugreport to track the issue reported here:
https://github.com/MrTheSoulz/NerdPack/issues/209#issuecomment-309234326

> @MrTheSoulz
> Morning sir,
> I found the function "buff.count" is not run on non-English wow.
> 
> {'195182', 'player.buff(195181).count<=6&talent(3,1)&target.inFront&target.inMelee'},

**Comment by zy4944796** [comment]
@MrTheSoulz Thank you sir.
