### ISSUE TITLE
Where is icons to toggle

### ISSUE THREAD

**Issue by ngmafia** [MrTheSoulz/NerdPack#211]
where are the icons files for toggles.

**Comment by adde88** [comment]
1. Open wowhead.com
2. Search for anything that has an icon. Abilities, spells, items, etc.
3. Click into the specific spell, item, ability that you found. Example: http://www.wowhead.com/spell=781/disengage
4. Left-Click on the ICON that appears on that website.
5. This will open another menu, which contains the icon-string that can be used with NerdPack.
6. PROFIT!

![WowHead](https://i.imgur.com/JZblFE0.png)
