### ISSUE TITLE
Recursive conditions "Cond1(Cond2(VAL))"

### ISSUE THREAD

**Issue by Noelpqr** [MrTheSoulz/NerdPack#214]
Like area(UI(abd),UI(cd))

**Comment by adde88** [comment]
You can customize it to a degree.
Example: 
```LUA
{'SPELL_NAME', 'player.area(40).enemies>UI(x_ENE)'},
```

But going even further and customizing the area function in itself would be cool.
Like this:
```LUA
{'SPELL_NAME', 'player.area(xVAR).enemies>UI(x_ENE)'},
```
xVAR is the same as UI(xVAR)

**Comment by MrTheSoulz** [comment]
at this point, i could enable this with a single line, i just dont know if it would break anything yet, thats why i havent done so already...

just saying its now forgotten 👍

**Comment by Noelpqr** [comment]
No Risk, No Gain ..
"It would be great if you  direct us to how to do it and let us take the risk

**Comment by MrTheSoulz** [comment]
@Noelpqr 
https://github.com/MrTheSoulz/NerdPack/blob/master/system/dsl.lua#L102
bellow that line add
`Args = DSL.Parse(Args, Spell, Target)`
