### ISSUE TITLE
Parser fails when spells have parentheses in them "Rejuvenation (Germination)"

### ISSUE THREAD

**Issue by ngmafia** [MrTheSoulz/NerdPack#220]
Not recognize buff "Rejuvenation (Germination)" in rotation script

**Comment by adde88** [comment]
Could you please post the line from your CR where you're trying to use this condition?

**Comment by ngmafia** [comment]
{'Rejuvenation', 'player.health < 90 & !player.buff(Rejuvenation (Germination))'},
or 
{'Rejuvenation', 'player.health < 90 & !player.buff(155777)'},

**Comment by adde88** [comment]
To compare. This is what i'm using, and it's working:
```LUA
{'Rejuvenation', 'talent(6,3)&buff(Rejuvenation)', 'lnbuff(Rejuvenation (Germination))'},
```

**Comment by adde88** [comment]
Do you get any error-messages when trying to execute it?

**Comment by Noelpqr** [comment]
you are not using English client, right?

**Comment by ngmafia** [comment]
Not, im using spanish client but all the other lines in the script work fine. The only problem is this buff.

**Comment by ngmafia** [comment]
> Do you get any error-messages when trying to execute it?
Not, dont see any error-messages

**Comment by MrTheSoulz** [comment]
this error is related to a dsl limitation.
The dsl is unable to parse buffs with parentheses on it, it asumes its a argument.

**Comment by ngmafia** [comment]
sorry my ignorance but what is dsl limitation?

**Comment by ngmafia** [comment]
`{'Rejuvenation', 'talent(6,3)&buff(Rejuvenation)', 'lnbuff(Rejuvenation (Germination))'},`

Dont work for me

**Comment by Noelpqr** [comment]
use spell id for germ and it will work

**Comment by ngmafia** [comment]
Dont work, rejuvetation still casting when i have germination. The idea is rejuvenation casting only when dont have germination.

**Comment by Kleei** [comment]
> **ngmafia**
> {'Rejuvenation', 'player.health < 90 & !player.buff(Rejuvenation (Germination))'},
> or
> {'Rejuvenation', 'player.health < 90 & !player.buff(155777)'},

Maybe because you have no target ? try this : 

{'Rejuvenation', 'talent(6,3) & player.health <= 90 & !buff(Rejuvenation (Germination))', 'player'},

This is mine and it's working like charm ;)

{'Rejuvenation', 'talent(6,3) & lowest.health <= UI(lowestgermination) & !buff(Rejuvenation (Germination))', 'lowest'},

**Comment by ngmafia** [comment]
I have target, to 'player', 'tank', etc... and not, i have spanish client but all other skills work fine. And look your script and see if your rejuvenation continue work when germination is active cuz i had the same line in other script and rejuvenation work but continue casting when germination is active and i want casting only when germination is not active.

**Comment by Kleei** [comment]
all is working fine on my cr. try to change language client to eng and see what is happens.

**Comment by Kleei** [comment]
later i'll add here a short video with proof.

**Comment by ngmafia** [comment]
What NP version use? And where can i watch this video?

**Comment by Kleei** [comment]
latest commit of NeP.
[https://www.youtube.com/watch?v=TwNWN_h43_I](url)

**Comment by ngmafia** [comment]
This work changing lenguage client, thx mate.
