### ISSUE TITLE
Conditions Enemies Fakeunit

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#221]
@MrTheSoulz I'm having trouble with "enemies" fakeunit again..
I'll show you the pics
If you look at the code. I clearly put the range condition in this time and it's still trying to spam mobs further away than 40 range.:
https://images.discordapp.net/attachments/206137918698422272/330239060872396820/Naamloos.png?width=1235&height=659
See here. The Fledgling Fel Bad. Further away than 40 range and still spamming it. It doesn't blacklist the unit either:
https://images.discordapp.net/attachments/206137918698422272/330239325960798208/Naamloos2.png
seems like it doesn't like the conditions xD
also not listening to "incombat"

**Comment by Yobleed** [comment]
this is the CR 
https://github.com/Yobleed/NerdPack-Yobleed/blob/master/rotations/Priest/shadow.lua

**Comment by Yobleed** [comment]
line 241 - 255

**Comment by MrTheSoulz** [comment]
Should be fixed with the new helpers.lua update
