### ISSUE TITLE
Shadowpriest

### ISSUE THREAD

**Issue by aeonabyss** [MrTheSoulz/NerdPack#23]
So, same issue as w/ insanity:
I cannot get Void Bolt to cast while under Voidform.

{'228266', 'player.buff(194249)'},  -- Void Bolt, (Voidform)

There are multiple IDs for VB and VF, so... not sure which one(s) will ultimately be used, but I went through ever combination, including typed out names, and none worked.

PM me when you get this and we can discuss.

**Comment by MrTheSoulz** [comment]
```
--Void Bolt on cooldown.
{'!Void Eruption', 'player.buff(Voidform)' },
```
Spells that morph can still be called using theyr original name
