### ISSUE TITLE
LUA Error om.lua:67 - script ran too long

### ISSUE THREAD

**Issue by winnerwinnington** [MrTheSoulz/NerdPack#230]
Message: Interface\AddOns\NerdPack\system\om.lua:67: script ran too long
Time: 07/09/17 14:33:20
Count: 1
Stack: Interface\AddOns\NerdPack\system\om.lua:67: script ran too longInterface\SharedXML\SharedBasicControls.lua:204: in function origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
Interface\AddOns\NerdPack\system\om.lua:67: in functionGet'
Interface\AddOns\NerdPack-CombatHelper\Targets.lua:79: in function `Target'
Interface\AddOns\NerdPack-CombatHelper\Targets.lua:103: in function <Interface\AddOns\NerdPack-CombatHelper\Targets.lua:99>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

**Comment by MrTheSoulz** [comment]
Is this still valid? did it happen again?

**Comment by Kleei** [comment]
not with om.lua for now but sometimes i get with general.lua  "script ran to long"

**Comment by MrTheSoulz** [comment]
Starting with MoP blizz added a maximum time that a cript is allow to run for while in combat, i dont know the exact maximum time but this means that if your computer for some reason has a cpu spike that causes it to hang momentarily it will crash nep...
The solution is to either make nep faster or run everything in a pcall wich would cause overhead.

Im researching on how i should aproch these random timeouts
