### ISSUE TITLE
LibArtifact Data-1.0.lua:174

### ISSUE THREAD

**Issue by salfisher** [MrTheSoulz/NerdPack#232]
Hi, i've this problem after 5 minutes of run script, is it possible to fix it?
Message: NerdPack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:174: attempt to index local 'info' (a number value)
Time: 07/11/17 01:35:28
Count: 1
Stack: ...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:174: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:167>
...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:242: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:233>
...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:258: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:254>
...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:321: in function `?'
...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68: in function <...ack\Libs\LibArtifactData-1.0\LibArtifactData-1.0.lua:68>

Locals: artifactID = nil
traits = <table> {
}
powers = <table> {
 1 = 40
 2 = 41
 3 = 42
 4 = 43
 5 = 44
 6 = 47
 7 = 49
 8 = 50
 9 = 51
 10 = 52
 11 = 53
 12 = 54
 13 = 350
 14 = 351
 15 = 352
 16 = 353
 17 = 1118
 18 = 1275
}
(for index) = 1
(for limit) = 18
(for step) = 1
i = 1
traitID = 40
info = 205273
(*temporary) = 40
(*temporary) = 205273
(*temporary) = 105280
(*temporary) = 1
(*temporary) = 1
(*temporary) = 0
(*temporary) = 0.72323298454285
(*temporary) = "attempt to index local 'info' (a number value)"
GetPowers = <function> defined =[C]:-1
GetPowerInfo = <function> defined =[C]:-1
GetSpellInfo = <function> defined =[C]:-1
artifacts = <table> {
 knowledgeMultiplier = 1
 knowledgeLevel = 0
}

**Comment by MrTheSoulz** [comment]
Related: https://github.com/MrTheSoulz/NerdPack/issues/218

**Comment by MrTheSoulz** [comment]
Related: https://github.com/MrTheSoulz/NerdPack/issues/218

**Comment by salfisher** [comment]
Resolved...
i've updated the libartifact data to 1.1.1 version from wowcurse ;)
https://mods.curse.com/addons/wow/libartifactdata-1-0#t1:other-downloads

ty ^:D

**Comment by MrTheSoulz** [comment]
I've downgraded the one included with NeP from 1.2 to 1.1.1
thanks for the tip!
