### ISSUE TITLE
beastmaster rotation not work

### ISSUE THREAD

**Issue by mujw** [MrTheSoulz/NerdPack#238]
zylla's beastmaster rotation not work with todays version. Kill command will not cast.
 Yesterday version was working fine

**Comment by mujw** [comment]
fixed

**Comment by mujw** [comment]
not fixed 

still not working

**Comment by adde88** [comment]
Please post errors regarding combat-routines on the repository of the developer of the combat-routine.
It makes it alot easier for the developer to keep track on the errors.
If NerdPack gets updated and it breaks the CR, then the developer needs to update his CR.

**Comment by MrTheSoulz** [comment]
Might be related to:
https://github.com/MrTheSoulz/NerdPack/issues/242

Is your wow client in english?

**Comment by mujw** [comment]
Chinese

**Comment by MrTheSoulz** [comment]
You'll need to add the ids for the spells, read how here;
https://github.com/MrTheSoulz/NerdPack/wiki

**Comment by mujw** [comment]
where to find spess id? thanks

**Comment by MrTheSoulz** [comment]
https://github.com/MrTheSoulz/NerdPack/wiki

**Comment by mujw** [comment]
I add these in the lua file but it is not working ,nerdpack cannot find this lua in game
need help thx..


local spell_ids = {
     [A Murder of Crows] = #131894,
     [aspect Of The Wild] = #193530,
     [barrage] = #120360,
     [bestial Wrath ] = #19574,
     [binding Shot] = #109248,
     [chimaera Shot] = #53209,
     [cobra Shot] = #193455,
     [concussive Shot] = #5116,
     [counter Shot] = #147362,
     [dire Frenzy] = #217200,
     [disengage] = #781,
     [intimidation] = #19577,
     [kill Command] = #34026,
     [misdirection] = #34477,
     [multi Shot] = #2643,
     [stampede] = #201430,
     [Titan\'s Thunder] = #207068,
     [volley] = #194386
}


any mistake?

**Comment by MrTheSoulz** [comment]
Remove the # from the ids

**Comment by MrTheSoulz** [comment]
Example:
["Volley"] = 194386

**Comment by mujw** [comment]
thx I will try it

**Comment by mujw** [comment]
is ["Volley"]  or [Volley] ?

are there any quick method to transfer all class spells into correct format instead of writing them down? 
thank you
