### ISSUE TITLE
NerdPack\actions.lua:209: Usage: GetItemCooldown(itemID)

### ISSUE THREAD

**Issue by adde88** [MrTheSoulz/NerdPack#239]
```
1x NerdPack\actions.lua:209: Usage: GetItemCooldown(itemID)
[C]: ?
NerdPack\actions.lua:209: in function <NerdPack\actions.lua:203>
NerdPack\system\parser.lua:135: in function `Parse'
NerdPack\system\parser.lua:107: in function <NerdPack\system\parser.lua:103>
(tail call): ?
(tail call): ?
NerdPack\system\parser.lua:150: in function <NerdPack\system\parser.lua:143>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
```

Tried printing the vars within the Add('item function
item, item.id, GetItemSpell(item.spell)
and it printed some tables, and then my ring from Karazhan before crashing.

**Comment by MrTheSoulz** [comment]
try changing to "item.id" instead of item.spell

**Comment by Kimbanjang** [comment]
> try changing to "item.id" instead of item.spell in NerdPack\actions.lua:209

i tried. but still crashing.

**Comment by Kimbanjang** [comment]
don't crashing after last commit(be1b8631fc2b6c7c4bd2d69e52103c2b5db4f189)
