### ISSUE TITLE
Diispells are not working correctly

### ISSUE THREAD

**Issue by Chiisato** [MrTheSoulz/NerdPack#24]
Sometimes it's trying to dispell effects that it can't, for example curse or not even a magic effect, it can be a random "undefined" debuff and it spams dispell trying to dispel it.

**Comment by MrTheSoulz** [comment]
Which class and spec is this happening? Or are they all affected?
I recently made some changes to the function, will check if i did not break it.

**Comment by Chiisato** [comment]
Priest, both Disc and Holy, haven't tried anything else yet

**Comment by MrTheSoulz** [comment]
Dispel's should work now with commit: 008b0c217208f741e088a742438f337169577ae5
However there is no debuff blacklist yet, will add this soon.

**Comment by Chiisato** [comment]
Awesome, a debuff blacklist would indeed be handy, thanks! <3
