### ISSUE TITLE
Problem with recend update

### ISSUE THREAD

**Issue by salfisher** [MrTheSoulz/NerdPack#242]
I've updated recend NerdPack and Nerdpack-protected and i have problem with yobleed rotation. I use oLUA (7.1.5). The Left Control (keybind not works) and also when im in voidform he didn't use shadow word: death spell........The problem it's NerdPack because with previous version everything works ok....another problem it's with AOE

`--SWD when target below 35
	{'!Shadow Word: Death', '!player.insanity >= 65 & !player.channeling(Void Eruption)','target'},`

**Comment by MrTheSoulz** [comment]
Is you client in english?
I belive the current version is having trouble with the localespells module

**Comment by salfisher** [comment]
Yes it's english with 7.1.5 patch

**Comment by MrTheSoulz** [comment]
Should be fixed
