### ISSUE TITLE
issue with states

### ISSUE THREAD

**Issue by Kleei** [MrTheSoulz/NerdPack#244]
"target.immune(all)"
doesn't work when mage are in "ice block" and maybe not only.

**Comment by adde88** [comment]
I opened system/tooltip.lua
And i checked out the function pPattern at line 10.
I tried printing the contents of the tables that are being processed at line 15.
```print(pattern[i])```

Then i attempted to dump the immune condition:
```/dump NeP.DSL:Get('immune')('player', 'all')```
It then prints out "dematerialize, deterrence, divine shield, ice block"
And the condition being dumped also returns false. (which was correct at the time)

Anyways, this shows that it manages to fetch the correct tables from locale/enUS.lua
And that it should be working, at least for enUS clients. Isn't that correct?

**Comment by adde88** [comment]
It does not display those tables when i use 'target' instead of 'player'.

**Comment by MrTheSoulz** [comment]
@adde88 did you have a target when you tried it?
it wouldnt even reach the func if the unit dosent exist

**Comment by adde88** [comment]
I tried it again now, printing the contents of the pattern table while dumping different stuff.
And it seems to display the tables as well now, when i use 'target'.

I got a list of stuff, like: dematerialize, divine shield, ice block, deterrence.

I guess those are the tables it are comparing against. Wouldn't this mean that it should work?
As the next line is to return true if it matches.

**Comment by MrTheSoulz** [comment]
This shiul be working...
