### ISSUE TITLE
issue with range condition

### ISSUE THREAD

**Issue by Noelpqr** [MrTheSoulz/NerdPack#245]
example
{'Death and Decay', '!player.buff(Death and Decay)& player.buff(Crimson Scourge)&talent(2,1)&target.inMelee ','player.ground'},
{'Blood Boil', '!target.debuff(Blood Plague)&target.range<10', 'target'},

Nep will cast them even when the range between target and player is more than what being on the condition

**Comment by MrTheSoulz** [comment]
`{function() print("hit") end, "target.range<10"},`
like i mentioned on discord, i tried this and it works fine...
what unlocker are you using?
