### ISSUE TITLE
New update issue :(

### ISSUE THREAD

**Issue by salfisher** [MrTheSoulz/NerdPack#247]
Keybinds doesnt work

First Error:

Message: Interface\AddOns\NerdPack-Overlays\core.lua:66: attempt to call method 'Hide' (a nil value)
Time: 08/01/17 23:14:35
Count: 1
Stack: Interface\AddOns\NerdPack-Overlays\core.lua:66: in main chunk

Locals: name = "NerdPack-Overlays"
Overlays = <table> {
 Version = 2
 GUI = <table> {
 }
}
NeP = <table> {
 Protected = <table> {
 }
 ActionLog = <table> {
 }
 FakeUnits = <table> {
 }
 Library = <table> {
 }
 ClassTable = <table> {
 }
 Actions = <table> {
 }
 Interface = <table> {
 }
 Artifact = <table> {
 }
 DSL = <table> {
 }
 Spells = <table> {
 }
 CR = <table> {
 }
 Core = <table> {
 }
 Tooltip = <table> {
 }
 RegisterCommand = <function> defined @Interface\AddOns\NerdPack\system\commands.lua:5
 OM = <table> {
 }
 BossID = <table> {
 }
 Listener = <table> {
 }
 Queue = <function> defined @Interface\AddOns\NerdPack\system\queuer.lua:11
 AddsID = <table> {
 }
}
F = <function> defined @Interface\AddOns\NerdPack-Overlays\core.lua:4
LibDraw = <table> {
 lines = <table> {
 }
 SetColorRaw = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:60
 Enable = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:419
 callbacks = <table> {
 }
 rotateY = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:92
 clearCanvas = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:392
 Box = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:308
 Sync = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:388
 line = <table> {
 }
 textures = <table> {
 }
 Distance = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:378
 rotateZ = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:104
 fontstrings = <table> {
 }
 Text = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:276
 Texture = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:230
 fontstrings_used = <table> {
 }
 rotateX = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:80
 canvas = <unnamed> {
 }
 Draw2DLine = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:140
 Circle = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:187
 GroundCircle = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:198
 Array = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:116
 DrawHelper = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:351
 textures_used = <table> {
 }
 Camera = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:382
 SetWidth = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:67
 Arc = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:211
 Line = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:71
 lines_used = <table> {
 }
 level = "BACKGROUND"
 SetColor = <function> defined @Interface\AddOns\NerdPack-Protected\external\LibDraw.lua:49
}
ObjectPosition = nil
UnitName = <function> defined =[C]:-1
UnitGUID = <function> defined =[C]:-1
UnitCombatReach = nil
UnitTarget = nil
UnitExists = <function> defined =[C]:-1
ReloadUI = <function> defined =[C]:-1
config = <table> {
 subtitle = "Settings"
 key = "NerdPack-Overlays"
 height = 500
 config = <table> {
 }
 title = "NerdPack-Overlays"
 width = 200
}
(*temporary) = nil
(*temporary) = <table> {
 parent = <table> {
 }
 elements = <table> {
 }
}
(*temporary) = "attempt to call method 'Hide' (a nil value)"

Second Error:
Message: Interface\AddOns\NerdPack\system\lib.lua:28: attempt to call field '?' (a nil value)
Time: 08/01/17 23:15:01
Count: 1
Stack: Interface\AddOns\NerdPack\system\lib.lua:28: in function <Interface\AddOns\NerdPack\system\lib.lua:20>
(tail call): ?
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:48: in function <Interface\AddOns\NerdPack\system\dsl.lua:43>
(tail call): ?
Interface\AddOns\NerdPack\system\dsl.lua:45: in function <Interface\AddOns\NerdPack\system\dsl.lua:43>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:96: in function `func'
Interface\AddOns\NerdPack\system\parser.lua:89: in function <Interface\AddOns\NerdPack\system\parser.lua:84>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:98: in function `func'
Interface\AddOns\NerdPack\system\parser.lua:89: in function <Interface\AddOns\NerdPack\system\parser.lua:84>
(tail call): ?
Interface\AddOns\NerdPack\system\parser.lua:143: in function <Interface\AddOns\NerdPack\system\parser.lua:134>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals: _ = <table> {
 Parse = <function> defined @Interface\AddOns\NerdPack\system\lib.lua:20
 Fetch = <function> defined @Interface\AddOns\NerdPack\system\lib.lua:16
 Add = <function> defined @Interface\AddOns\NerdPack\system\lib.lua:10
}
strg = "Zylla.hitcombo(Blackout Kick)"
args = nil
a = "Zylla"
b = "hitcombo(Blackout Kick)"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to call field '?' (a nil value)"
NeP = <table> {
 Media = "Interface\AddOns\NerdPack\Media\"
 ActionLog = <table> {
 }
 min_height = 25
 Locale = <table> {
 }
 BlacklistedDebuffs = <function> defined @Interface\AddOns\NerdPack\tables\blacklisted_auras.lua:54
 Globals = <table> {
 }
 Interface = <table> {
 }
 Artifact = <table> {
 }
 Commands = <table> {
 }
 Queuer = <table> {
 }
 Buttons = <table> {
 }
 Spells = <table> {
 }
 Helpers = <table> {
 }
 AddsID = <table> {
 }
 Config = <table> {
 }
 Listener = <table> {
 }
 Branch = "Beta8"
 Faceroll = <table> {
 }
 Protected = <table> {
 }
 Color = "00ff96"
 FakeUnits = <table> {
 }
 ButtonsSize = 40
 Library = <table> {
 }
 ClassTable = <table> {
 }
 Actions = <table> {
 }
 BossID = <table> {
 }
 min_width = 40
 Version = 1.8
 STs = <table> {
 }
 Tooltip = <table> {
 }
 Healing = <table> {
 }
 CR = <table> {
 }
 Core = <table> {
 }
 OM = <table> {
 }
 ByPassMounts = <function> defined @Interface\AddOns\NerdPack\tables\castable_mounts.lua:25
 Parser = <table> {
 }
 DSL = <table> {
 }
 CombatTracker = <table> {
 }
 Compiler = <table> {
 }
 ButtonsPadding = 2
}
strsplit = <function> defined =[C]:-1
libs = <table> {
 Rubim = <table> {
 }
 Zylla = <table> {
 }
}
unpack = <function> defined =[C]:-1

**Comment by MrTheSoulz** [comment]
update the modules aswell, use the toolbox
