### ISSUE TITLE
aoe code again dont work for me

### ISSUE THREAD

**Issue by ngmafia** [MrTheSoulz/NerdPack#249]
This is my line and worked before update
{AoE, 'toggle(aoe)&player.area(8).enemies>=2'},
{xCombat, 'target.range<8&target.infront&player.area(8).enemies<=1'},

Now AoE work all the time

**Comment by hgdubbe** [comment]
Can confirm, lines:
{'Templar\'s Verdict','player.area(8).enemies<2||!toggle(AoE)'},
{'Divine Storm', 'player.area(8).enemies>=2&toggle(AoE)'},
spam aoe while toggle(AoE) is activated and 2 or more enemies show up in the units list, no matter the distance

nredpack version: newest
protected version: newest
unlocker: tested with olua and ewt

**Comment by ngmafia** [comment]
Yep, range or distance parameter dont work i think
