### ISSUE TITLE
Clicking dead or people in another zone crashes your game

### ISSUE THREAD

**Issue by Chiisato** [MrTheSoulz/NerdPack#25]
Managed to replicate this, crash every single time

**Comment by MrTheSoulz** [comment]
Which unlocker?
If its FH try redownloading it.

**Comment by Chiisato** [comment]
FH, using latest version

**Comment by MrTheSoulz** [comment]
i havent been able to reproduce this, does it still hapen?

**Comment by Chiisato** [comment]
Seems to have been fixed, been unable to reproduce this myself. I'll reopen if this occurs again, thanks!
