### ISSUE TITLE
Is there anyone know how did Blizzard detect the plug-in,leading to a temporary freeze?

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#257]
last week,I receive a e-mail told me They found me had the illegal  third part plug-in,then temporary freeze 180 days .
In my impression, I used this plug-in in the arena only several times in that day.
Is there anyone have  the similar situations?

**Comment by MrTheSoulz** [comment]
What unlocker were you using?
What cr were you using?

**Comment by zy4944796** [comment]
@MrTheSoulz Good day sir.
I used EasyWoWToolbox,and cr was Nerdpack-Zylla or  NerdPack-Xeer.
