### ISSUE TITLE
Eye of Azshara Dispel

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#265]
NeP doesn't wanna Dispel "Polymorph: Fish" Debuff ID 197105

Could it be that this is blacklisted?

**Comment by MrTheSoulz** [comment]
I think theres a debuff blacklist, it would stop nep touching units with debuffs like that

**Comment by Yobleed** [comment]
could u take a look for me? I think this debuff is only specific for EoA

**Comment by Kleei** [comment]
no , is not blacklisted ... see [blacklisted auras](https://github.com/MrTheSoulz/NerdPack/blob/master/tables/blacklisted_auras.lua)
