### ISSUE TITLE
[Feature Request]: Blacklist/Whitelist of Spells to Interrupt

### ISSUE THREAD

**Issue by adde88** [MrTheSoulz/NerdPack#270]
It'd be awesome to have a blacklist/whitelist table for certain spells to NOT be interrupted, or to ONLY be interrupted (ignore all others).
Check a box in settings to activate whitelist-mode, or uncheck it to enable blacklist mode?

**Comment by subzrk** [comment]
It'd be awesome to have this Feature in NeP

**Comment by adde88** [comment]
I'm looking at the latest commits to DEV.
It looks like we should be able to do such a check in this function:

**NerdPack\luaengine\apis.lua : 56 **
```LUA
function NeP.API.Interrupt(spell)
  local name = NeP.API.CastingTime()
	if name == spell then
		return false
	end
	NeP.Protected.SpellStopCasting()
	return true
end
```

If we add a table, (gets filled with data from the CR settings), then we could a **NeP.API.SpellBlacklist(spell)** function that checks if the casted spell matches with anything in the table.

**Comment by MrTheSoulz** [comment]
Theres a table to blacklist in master

**Comment by adde88** [comment]
But that table is "aura specific" is it not?
I was thinking about a whitelist/blacklist of spells being casted, to avoid interrupting spells we want to skip.

**Comment by MrTheSoulz** [comment]
@adde88 ah, yes your right...
will add it to the new parser.
