### ISSUE TITLE
FireHack has issues with UseItem API

### ISSUE THREAD

**Issue by emulcube** [MrTheSoulz/NerdPack#273]
NerdPack v: 1.8 - Beta11
FireHack

error code

2x [ADDON_ACTION_FORBIDDEN] Addon 'NerdPack'  'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: ?
[C]: ?
[C]: in function `ObjectCall'
[string "Object Calls.lua"]:136: in function `UseItemByName'
NerdPack-Protected\generic.lua:32: in function `UseItem'
NerdPack\actions.lua:14: in function <NerdPack\actions.lua:14>
(tail call): ?
NerdPack\system\parser.lua:85: in function <NerdPack\system\parser.lua:75>
(tail call): ?
NerdPack\system\parser.lua:96: in function `func'
NerdPack\system\parser.lua:85: in function <NerdPack\system\parser.lua:75>
(tail call): ?
NerdPack\system\parser.lua:153: in function <NerdPack\system\parser.lua:137>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
InCombatSkipped

==========================================
{type = 'checkspin', width = 70, min = 0, max = 100, step = 1, text = 'healthstone',	key = 'P_HS', check = true, spin = 40},

{'#5512', 'item(5512).cooldown = 0 & item(5512).count > 0 & UI(P_HS_check) & player.health <=UI(P_HS_spin)'},

**Comment by MrTheSoulz** [comment]
what unlocker caused this?

**Comment by emulcube** [comment]
FireHack  
Usage error occurs.

**Comment by emulcube** [comment]
FireHack
Usage error occurs.

**Comment by emulcube** [comment]
There is still a problem with the 15-day update.

**Comment by hgdubbe** [comment]
putting a trinket in slot1 and using `/use 13` will output the same error (with other calls of course), so it's very likely to be firehack-problem
