### ISSUE TITLE
Request Count Dead Players

### ISSUE THREAD

**Issue by Yobleed** [MrTheSoulz/NerdPack#282]
Yobleed - Today at 10:58 AM
@MrTheSoulz  is there a way to count Dead players?
for example: if 1 player is dead I wanna use Ressurection
if more than 1 is dead I wanna use Mass Resurrection
Yobleed - Today at 11:02 AM
something like group.members.dead >= #

We already have the group.members condition registered.
So this would be the most logical maybe?

**Comment by Yobleed** [comment]
according to other players this is not to be found useful, may be closed

**Comment by MrTheSoulz** [comment]
Added area.dead, it counts dead units near the unit, dosent really check if its friendly or enemie tho....
