### ISSUE TITLE
Gatherbot Error

### ISSUE THREAD

**Issue by darkjacky** [MrTheSoulz/NerdPack#29]
Can you create a folder in the main folder called: "Gathering Profiles"? This will fix the error you get when trying to save a profile.
NerdPack\system\gatheringBot.lua:92: The file could not be opened.
[C]: in function `WriteFile'
NerdPack\system\gatheringBot.lua:92: in function <NerdPack\system\gatheringBot.lua:85>

(In that case you could also allow custom names.)

**Comment by MrTheSoulz** [comment]
Fixed, thanks.
Custom names are a bit tricky, trying to solve it tho.

**Comment by darkjacky** [comment]
It created a file but not a folder all you have to do is create the folder. And since you have done that now all that is left to do is create a text entrybox.
Also you can use https://www.fh-wow.com/apidocs/GetDirectoryFiles.php to get the files and make a list.

**Comment by MrTheSoulz** [comment]
Done: https://github.com/MrTheSoulz/NerdPack/commit/d4bc5ccad40aecc626add68b83570a285573dea5

**Comment by MrTheSoulz** [comment]
Theres a issue loading the profile...
