### ISSUE TITLE
missing state control

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#29]
Hi, looks like Nerdpack does not contain state control while Probably Engine had it before.
It was quite usable functionality to check unit states instead passing list of buff and debuffs thru filter.
Is it possible to add state control?
As NerdPack tool installs also DarkN-CR combat rotations, some (monk and paladin) does not work because controlling states.

**Comment by MrTheSoulz** [comment]
Hello, not sure what you mean by state controls.
Can you fill me in?

**Comment by MrTheSoulz** [comment]
You mean these?
https://gitlab.com/probablyengine/probably/blob/master/system/conditions/states.lua

Sure will add them

**Comment by MrTheSoulz** [comment]
Added with: 0a109952bd6c0179844abf268727d44d10ce95fc
Re-open this if you find issues with it :)
