### ISSUE TITLE
[Feature Request]: Interrupt if 2 or more enemies Interruptable

### ISSUE THREAD

**Issue by ivicask** [MrTheSoulz/NerdPack#290]
Would it be possible to add such condition so i can prioritize AOE interrupt spells over single target interrupt spells if 2 or more enemies around(in range) me are casting at the same time and are Interruptable.

**Comment by adde88** [comment]
Making such a condtition is surely possible. I'll be looking into it.

**Comment by MrTheSoulz** [comment]
added in DEV:  https://github.com/MrTheSoulz/NerdPack/commit/ec4aa3bdeef167395f18e3c2977c5d6e60215980
