### ISSUE TITLE
[DEV branch:] - NeP.Actions:('dispel')

### ISSUE THREAD

**Issue by adde88** [MrTheSoulz/NerdPack#293]
The new function is not working.
Debugging it atm, so it's just a heads up about the issue.

**Comment by adde88** [comment]
Added some prints to attempt debugging it.
It seems to support the usage of "'target" in the CR's (As the target, which it will inherit).
But not enemies (fakeunits/units)
Because **UnitExists()** doesn't know what enemy that is.

So it support target. Which means it should be dispelling targets, right?
Nope.

Not sure where the problem lies, tried adding prints like this example:
```LUA
NeP.Actions:Add('dispel', function(eval)
  if not _G.UnitExists(eval[3].target) then
		print("Dispel DEBUG: NO  UNIT EXISTS: ", eval[3].target)
		return
	end
	print('Dispel DEBUG: UNIT EXISTS: ', eval[3].target)
  for _, spellID, _,_,_,_,_, duration, expires in LibDisp:IterateDispellableAuras(eval[3].target) do
		print("Dispel DEBUG: CHECKING UNIT: ", eval[3].target)
    local spell = GetSpellInfo(spellID)
```

It finds the unit "target". But it does NOT print "CHECKING UNIT". Indicating that the for loop is not started. Should we rather use the OM? OR GetObjectCount()+GetObjectIndex()?

**Comment by MrTheSoulz** [comment]
Ya this requires a new parser, the current one wasnt designed to work with what i am doing...
