### ISSUE TITLE
Error: AddOn NerdPack-Protected attempted to call a forbidden function (UNKNOWN()) from a tainted execution path

### ISSUE THREAD

**Issue by LiquidAtoR** [MrTheSoulz/NerdPack#295]
Date: 2017-11-29 20:22:09
ID: 1
Error occured in: AddOn: NerdPack-Protected
Count: 1
Message: Error: AddOn NerdPack-Protected attempted to call a forbidden function (UNKNOWN()) from a tainted execution path.
Debug:
   [C]: ?
   [C]: pcall()
   NerdPack-Protected\generic.lua:48: test()
   NerdPack-Protected\core.lua:91:
      NerdPack-Protected\core.lua:88
Locals:
None
AddOns:
  Swatter, v7.5.5724 (TasmanianThylacine)
  WowheadLooter, v70300
  AckisRecipeList, v7.3.0.1
  AckisRecipeListQuickScan, v7.3.0.1
  AddOnSkins, v3.49
  AucAdvanced, v7.5.5724 (TasmanianThylacine)
  AucFilterBasic, v7.5.5724 (TasmanianThylacine)
  AucFilterOutlier, v7.5.5724.5459(7.5/embedded)
  AucMatchUndercut, v7.5.5724.5585(7.5/embedded)
  AucStatHistogram, v7.5.5724 (TasmanianThylacine)
  AucStatiLevel, v7.5.5724 (TasmanianThylacine)
  AucStatPurchased, v7.5.5724 (TasmanianThylacine)
  AucStatSales, v7.5.5724.5598(7.5/embedded)
  AucStatSimple, v7.5.5724 (TasmanianThylacine)
  AucStatStdDev, v7.5.5724 (TasmanianThylacine)
  AucStatWOWEcon, v7.5.5724.5613(7.5/embedded)
  AucUtilAHWindowControl, v7.5.5724.5575(7.5/embedded)
  AucUtilAppraiser, v7.5.5724.5719(7.5/embedded)
  AucUtilAskPrice, v7.5.5724.5599(7.5/embedded)
  AucUtilAutoMagic, v7.5.5724.5686(7.5/embedded)
  AucUtilCompactUI, v7.5.5724.5715(7.5/embedded)
  AucUtilEasyBuyout, v7.5.5724.5576(7.5/embedded)
  AucUtilFixAH, v7.5.5724 (TasmanianThylacine)
  AucUtilItemSuggest, v7.5.5724.5651(7.5/embedded)
  AucUtilPriceLevel, v7.5.5724.5633(7.5/embedded)
  AucUtilScanButton, v7.5.5724.5631(7.5/embedded)
  AucUtilScanFinish, v7.5.5724.5720(7.5/embedded)
  AucUtilScanProgress, v7.5.5724.4979(7.5/embedded)
  AucUtilScanStart, v7.5.5724.5347(7.5/embedded)
  AucUtilSearchUI, v7.5.5724.5721(7.5/embedded)
  AucUtilSimpleAuction, v7.5.5724.5705(7.5/embedded)
  AucUtilVendMarkup, v7.5.5724.4828(7.5/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BagBrother, v
  BeanCounter, v7.5.5724 (TasmanianThylacine)
  Collectinator, v7.2.5.1
  Configator, v5.1.DEV.431(/embedded)
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.68
  ElvUICastBarOverlay, v1.06
  ElvUICustomMedia, v1.2
  ElvUICustomTweaks, v1.35
  ElvUILocPlus, v2.27
  ElvUIMicrobar, v1.83
  ElvUITB, v1.17
  ElvUIVisualAuraTimers, v1.51
  Enchantrix, v7.5.5724 (TasmanianThylacine)
  EnchantrixBarker, v7.5.5724 (TasmanianThylacine)
  EnhancedPetBattleUI, v2.13
  GarrisonCommanderBroker, v2.18.5 1.1.0
  GatherMate2, v1.41
  GatherMateSharing, vv1.10
  Informant, v7.5.5724 (TasmanianThylacine)
  LibExtraTip, v5.12.DEV.430(/embedded)
  NerdPack, v
  NerdPackCombatHelper, v
  NerdPackCustomKeybinds, v
  NerdPackFSH, v
  NerdPackInvalid, v
  NerdPackKleei, v
  NerdPackLocaleSpells, v
  NerdPackOverlays, v
  NerdPackPB, v
  NerdPackProtected, v
  NerdPackRabbs, v
  NerdPackSilver, v
  NerdPackSVR, v
  NerdPackTrip, v
  NerdPackXeer, v
  NerdPackYobleed, v
  NerdPackYumad, v
  NerdpackZylla, v2.7-7.3.0-release
  Omen, v3.1.12
  Rarity, v1.0
  RarityOptions, v
  Recount, vv7.3.2a
  Stubby, v7.5.5724 (TasmanianThylacine)
  TipHelper, v5.12.DEV.405(/embedded)
  ZygorGuidesViewer, v6.1
  BlizRuntimeLib_enUS v7.3.2.70300

**Comment by LiquidAtoR** [comment]
No unlocker loaded or active since all the free good ones are gone, could it be related to that?

**Comment by MrTheSoulz** [comment]
Yes, This just means you're  not unlocked.
