### ISSUE TITLE
My error speech not working

### ISSUE THREAD

**Issue by Jefferyasbell** [MrTheSoulz/NerdPack#297]
My error speech and error txt is not working when I activate your Nerdpack and all other files that go along with it. I have narrowed it down to your addon by enabling and disabling it several times. there is no lua error Just no speach or txt. I even dissabled all addons then one addon a time added them back it was when I added Nerdpack by its self and no sound from errors. all other sounds in game work except that.

**Comment by MrTheSoulz** [comment]
erros are disabled by nep on purpose:
https://github.com/MrTheSoulz/NerdPack/blob/master/system/debug.lua#L9

may be related?
