### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by gongmang1** [MrTheSoulz/NerdPack#3]
1.EWT "Advanced LUA Unlock" , gatherbot not shows      [line 34]
2.Overlays,      draw line or circle makes a lot of lags
3.fishingbot not working   [IsObjectCreatedBy error?]
4.what is DH id?
5. spell cast has lags.

**Comment by MrTheSoulz** [comment]
1- EWT problem was fixed
2- thats normal
4- DH? Demon hunter? 577 = Havoc, 581 = Vengeance
5- lags? can you try the new version see if that helps?

Still Checking (3)

**Comment by gongmang1** [comment]
5.    cast a spell   →  GCD  → delay 200~500 → cast next spell

**Comment by MrTheSoulz** [comment]
Try the new update, should fix it by default
