### ISSUE TITLE
When will be the roration upgrade to 8.0? 

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#305]
@MrTheSoulz  Good day sir.Could  you tell me how soon you will upgrade it to 8.0.

**Comment by MrTheSoulz** [comment]
already done.

**Comment by zy4944796** [comment]
@MrTheSoulz Already done? sorry ,I don't find any module update in the list of NerdPack ToolBox .All the  modules had been upgraded since 5- 7 months ago.
