### ISSUE TITLE
Don't Update Mastertoggle Icon after changed talent or changed Specialization

### ISSUE THREAD

**Issue by Kimbanjang** [MrTheSoulz/NerdPack#325]
Nerdpack Ver : https://github.com/MrTheSoulz/NerdPack/commit/71231f6387c454eaff890ac21bb2cc0fe6942c98

L.Interface:UpdateIcon('mastertoggle', eval[1].icon) (/system/parser.lua:160) is no work after changed talent or changed Spec or changed Spell(like change Death Sweep to Blade Dance used Metamorphosis)

i use nerdpack and keysender base color-picker(selfmade). so i need ur help for fix it.

**Comment by MrTheSoulz** [comment]
need to force re-compile, will look into it

**Comment by MrTheSoulz** [comment]
should be done now
