### ISSUE TITLE
the hunter combat routines does not work

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#34]
i am a newcomer to this  add-ons.
the add-ons is loaded successfully,and the  mastertoggle is showed in the game and enabled,but the combat routines does not work.
this is my screenshots.does i forget something necessary to set?
![20160904085016](https://cloud.githubusercontent.com/assets/8578753/18228337/ccb13d36-727c-11e6-95ce-94d2db456e26.png)

**Comment by MrTheSoulz** [comment]
What do you mean by it dosent work?
I need more details.
What do you want it to do? Automated?
If so you need a lua unlocker, are you using one?

**Comment by zy4944796** [comment]
@MrTheSoulz
 Thank your reply  very much,i thought these addons are for auto fightting by AFK Like honorbuddy,am I wrong?
My character does not fight against the enemy automatically,no auto interrupts ,no auto aoe.
I test with DeadKing,Paladin,and Hunter.
Although Paladin can auto  targets, automated facing and movements,it do not auto fight yet.
I run EWT(easy wow toolbox) well,and set the option "Advanced Lua Unlock" in EWT.the combat helperV1.1 seem like wok fine for Paladin.
I did see a message "[nep]:Found:EasyWoWToolBox"in chat saying when i click the red unlock option,but it also seem like no use .
![20160904143047](https://cloud.githubusercontent.com/assets/8578753/18229452/97496d3c-72ac-11e6-9684-efdfb43c6d37.png).

**Comment by zy4944796** [comment]
@MrTheSoulz 
the Combot helper V1.1 does not work fine for DeadKnight by my test,but work well for Paladin
.
![20160904143649](https://cloud.githubusercontent.com/assets/8578753/18229493/fd0de228-72ad-11e6-8cf6-c27160689546.png)

**Comment by zy4944796** [comment]
@MrTheSoulz Nobody confront the problems like this?

**Comment by MrTheSoulz** [comment]
Yes, this will automatr everything if you use a unlocker, wich you are.
Is your wow client in english? My current crs will only work in english clients.

**Comment by zy4944796** [comment]
@MrTheSoulz  Yes,I think the problem

**Comment by zy4944796** [comment]
@MrTheSoulz  Thank you very much,The cause of the problem is the language of client,and I fix it.
Best regards to you .
