### ISSUE TITLE
Dynamic target

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#35]
Hi!

Maybe this is not really defect as it did not work properly with PE as well. Please take it as feature request if possible to deal with.
Problem is with dynamic target selection like you have in code examples (MTS Routines): areaRend,  aDot etc.
It will not work always as expected:
{ 'Spell', '@setdynamictarget'  },
In some cases target will be "target" even if dynamic selector sets some other unit!

Reason is that conditions checked after target is set in place (Engine.Parse).
In some case it works if target is set to "nil". But seems it fails in any case if it is inside larger table structure.
{ 'Spell', '@setdynamictarget', nil  },

Currently there is workaround - that works as expected:
{{
  { 'Spell'},
}, '@setdynamictarget'  },

Br Fan

**Comment by MrTheSoulz** [comment]
I think i know the reason, will look into it.

**Comment by MrTheSoulz** [comment]
Temp fix with: https://github.com/MrTheSoulz/NerdPack/commit/91f79a025ff1a41e3210dd3c6dcced76abc2da38

Re-open this if needed.
