### ISSUE TITLE
Healing - misstyped variables

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#37]
Row 37: 					healthRaw = health,
probably correct is:			healthRaw = healthRaw,

Row 58:					prio = prio
Probably correct is:			prio = Obj.prio

Row 173:		target = player
there is no variable player, isit 'player'?

**Comment by MrTheSoulz** [comment]
Fixed in: https://github.com/MrTheSoulz/NerdPack/commit/a6b24b7040fc205b80cca3c013fd94edf5d66c81
