### ISSUE TITLE
A couple of Issues I have found.

### ISSUE THREAD

**Issue by darkjacky** [MrTheSoulz/NerdPack#4]
The range feature seems a bit broken. This is because it does not take into account the target box (I guess). (with range feature I mean the overlay green circle.)

In the GUI of the fishing bot I am unable to scroll down to select another bait.

When clicking the objects manager list it gives this error:
NerdPack\system\ObjectManager\ListGUI.lua:296: attempt to index local 'statusBar' (a nil value)

In the Information tab the Forums link is broken. It links to ownedcore and you get "Invalid Thread specified."

The rest seems fine. I am doing great dps. And I am happy about that.
If you need help with anything just say so :) (non GUI stuff)

**Comment by MrTheSoulz** [comment]
I have some Ideas for the range overlay, will see what i can do.
Will fix the rest soon, Thanks! :)

**Comment by MrTheSoulz** [comment]
Ive sent some comits wich should fix everything you have reported, please let me know if otherwise.

Thanks again, MTS.
