### ISSUE TITLE
Arcane charges missing from class conditions

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#42]
Hi,

Added with Legion: http://wow.gamepedia.com/PowerType
looks like this missed from class conditions:

RegisterConditon('arcanecharges', function(target, spell)
   return UnitPower(target, SPELL_POWER_ARCANE_CHARGES)
end)

**Comment by MrTheSoulz** [comment]
Added in: https://github.com/MrTheSoulz/NerdPack/commit/baae11d3a6383c915cdc087e8ca77fc310e2a0fa
Thanks!
