### ISSUE TITLE
CR dont work after latest update

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#43]
I have Holy Paladin CR that stopped working with the latest update.

I changed the keybind and toggle but it still dont work.

[2x Gabbz Combat Rotation\core.lua:36: attempt to call upvalue 'Parse' (a nil value)
Gabbz Combat Rotation\core.lua:36: in function <Gabbz Combat Rotation\core.lua:35>
(tail call): ?
(tail call): ?
(tail call): ?
NerdPack\system\dsl.lua:80: in function <NerdPack\system\dsl.lua:74>
(tail call): ?
NerdPack\system\engine.lua:362: in function `Parse'
NerdPack\system\engine.lua:342: in function `Parse'
NerdPack\system\engine.lua:342: in function `Parse'
NerdPack\system\engine.lua:385: in function `callback'
NerdPack\system\timer.lua:12: in function <NerdPack\system\timer.lua:8>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:](url)

**Comment by MrTheSoulz** [comment]
As we discussed in Discord, in the new core NeP.DSL.parse waa renamed to NeP.DSL.Parse
