### ISSUE TITLE
I try to make the addons work fine in chinese client ,but it doesn't work.any help?

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#45]
@MrTheSoulz ,good day.
The addons does not  work fine in chinese client,so I want to make some changes for localization.
I am a player from china,and I am a 2 years experience C++  programmer,So Learning Lua is not the prolem with reading the addons's code .
I replaced the english abilitys name of blood knight for chinese in blood.lua,but it doesn't work.
Could you tell me how can i do this localization job?
Maybe my fault is that I think it's too easy.
Here is the code fragment in blood.lua after my amending :
local ST = {
	--Blood Boil to maintain Blood Plague.
	{'血液沸腾', '!target.debuff(Blood Plague)'},
	--Death and Decay whenever available. Watch for Crimson Scourge procs.
	
	--Marrowrend to maintain 5 undefined.
	{'骨髓分裂'},
	--Blood Boil with 2 charges.
	{'血液沸腾', 'player.spell(Blood Boil).charges >= 2'},
	--Death Strike to dump Runic Power.
	{'灵界打击', 'player.energy >= 75'},
	--Heart Strike as a filler to build Runic Power.
	{'心脏打击'}
}

Best regard to you.

**Comment by MrTheSoulz** [comment]
You were just in time, i was working on a way to make english names work on any locale.
All you have to do is add the english name and the SpellID into this:
https://github.com/MrTheSoulz/NerdPack/blob/master/locale/Spell_IDs.lua

To find the SpellD, use idtip: https://mods.curse.com/addons/wow/spellid

If you dont know the spell name in english, use: http://www.wowhead.com/spell=SPELLID
Replace the SPELLID with the id you got from idtip.

**Comment by zy4944796** [comment]
@MrTheSoulz Thank you very much.Best regards.

**Comment by zy4944796** [comment]
@MrTheSoulz ,Here is the fragment that  Death Knight SpellID appended,may this can be shared with others. 

--Death Knight
	  --Blood
    ["Asphyxiate"] = {221562},
	["Blood Boil"] = {50842},
	["Heart Strike"] = {206930},
	["Death Strike"] = {49998},
	["Death Grip"] = {49576},
	["Marrowrend"] = {195182},
	["Death's Caress"] = {195292},
	["Mind Freeze"] = {47528},
	["Dancing Rune Weapon"] = {49028},
	["Death and Decay"] = {43265},
	["Wraith Walk"] = {212552},
	["Rune Tap"] = {194679},
	["Consumption"] = {205223},
	["Dark Command"] ={56222},
	  --Frost
	["Icebound Fortitude"] = {48792},
	["Pillar of Frost"] = {51271},
	["Frost Strike"] = {49143},
	["Remorseless Winter"] = {196770},
	["Howling Blast"] = {49184},
	["Anti-Magic Shell"] = {48707},
	["Chains of Ice"] = {45524},
	["Control Undead"] = {111673},
	["Obliterate"] = {49020},
	  --Unholy
	["Army of the Dead"] = {42650},
	["Summon Gargoyle"] = {49206},
	["Scourge Strike"] = {55090},
	["Death Coil"] = {47541},

**Comment by MrTheSoulz** [comment]
Thanks :)
