### ISSUE TITLE
all toggles except mastertoggle

### ISSUE THREAD

**Issue by NerdFan** [MrTheSoulz/NerdPack#46]
Hi,

After latest changes seems that custom button toggles are always ON.

**Comment by MrTheSoulz** [comment]
Does this still happen with the lastest stuff?
If so try to rename your WTF folder, and see if it works.

**Comment by NerdFan** [comment]
It is not about visual thing - all buttons works as expected and they changes their statuses and description after clicking. Problem is about handling toggle statuses in code with syntax:
{ 'spell', 'toggle.some' },
On that case toggle real status will not affect processing as it is passed always like "ON" - I have no idea what status really passed.
If I traced RegisterdCondition 'toggle' then only toggle value that handled there was 'mastertoggle' - no other values passed there at all. At first I tough that this is simple string handling issue but seems not.
Same time it looks like key modifiers also does not work - but I did not check them.
I will try to debug it more later!

**Comment by NerdFan** [comment]
Update - after latest (between yesterday and today) changes toggles are always OFF!
Detailed reason is here:

This spell will pass next Parse path
{ 'Spell', 'toggle.mytoggle' },

```
NeP.Timer.Sync("nep_parser", function()
	local Running = NeP.DSL.Get('toggle')(nil, 'mastertoggle')
	if Running then
		if Engine.SelectedCR then
			if not Engine.forcePause then
				Engine.Parse(table)
Only Parse called no more special handlings!

function Engine.Parse(table)
	for i=1, #table do
		local aR, tP = table[i], type(table[i][1])
tP -> string
		local spell, conditions, target = aR[1], aR[2], aR[3]
spell -> 'Spell'
conditions -> toggle.mytoggle
target -> nil
		local Iterate, spell, sI = canIterate(spell)
Iterate -> True
		if Iterate then
			elseif tP == 'string' then
				local target, isGroundCast = checkTarget(target)
				if target then
target was 'nil' - no processing at all!
```
ok, I did another try with target:
{ 'Spell', 'toggle.mytoggle', 'player' },

it ends here:
```
local function ProcessCondition(Strg, args, spell)
strg -> toggle.mytoggle
args -> nil
spell -> nil
	if DSL.Conditions[Strg] then
there is no such condition like 'toggle.mytoggle'
	end
	local unitId, rest = strsplit('.', Strg, 2)
unitId: toggle
rest: mytoggle
	if UnitExists(unitId) then
Unit 'toggle' does not exists
	end
end
```

NB! there is also uninitialised (Global) variable 'spell' here:
```
local function ProcessString(Strg)
		return ProcessCondition(Strg, Args, spell)
```

**Comment by MrTheSoulz** [comment]
The reason they dont work is beacuase they dont exist:
* toggle.key as been replaced with toggle(key)
* keybinds are now keybind(key)
* modifiers no longer exist.

**Comment by MrTheSoulz** [comment]
Toggles had a bug in them wich has been fixed
