### ISSUE TITLE
I found the a problem about  the MTS_Routines don't fight aginst the boss When the boss is great size,is this a bug?

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#47]
@MrTheSoulz My character is Death Knight,a melee DPS specs.the MTS_Routines's melee range  have seemed too small to run well when the boss or enemy has a great size.
I have tested with the behaviour several times, and I am sure the  problem is about the range of melee specs.
When the boss  is too high or too big,I must be directly below the boss ,a very small range,the routine starts to run,otherwise I step out of the small range,the routine stops.
Is there any solution about this?
Dose any one confront this bug?
I will be waiting online for your help.
Thank you .

**Comment by MrTheSoulz** [comment]
Thanks, will look into this

**Comment by MrTheSoulz** [comment]
This should be fixed now.
