### ISSUE TITLE
The latest Upgraded version does not run in other language,but work fine in english client.

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#52]
I have downloaded the latest version you upgraded today,and replaced the older version.With testing several characaters  ,I am sure it does not work in chinese client.
It does not work well again until  I  change the language to english.
Then I recovered the last version copy and change the wow client  language to chinese back,it work fine.

**Comment by MrTheSoulz** [comment]
Should be fixed now, thanks to @vorus PR
