### ISSUE TITLE
Toggle Cooldowns

### ISSUE THREAD

**Issue by jrubimf** [MrTheSoulz/NerdPack#54]
dumping NeP.DSL.Get("toggle")(nil, "coodowns") will always return false.

Hotkeys not working too.

**Comment by MrTheSoulz** [comment]
![image](https://cloud.githubusercontent.com/assets/5899335/18634891/e6c4e754-7e7a-11e6-966f-ba61ee9183dd.png)
/dump NeP.DSL.Get("toggle")(nil, "cooldowns")

**Comment by tw88** [comment]
Cooldown dont seem to work for me with the newest version, the value dumps to true

**Comment by tw88** [comment]
nvm fixed it - the NerdPack-DarkN-CR is using the old "modifiers"
