### ISSUE TITLE
spell.charges wrong count

### ISSUE THREAD

**Issue by macedoniazxv** [MrTheSoulz/NerdPack#58]
simpl: spell.charges <= 1.5 dont work

i edit condidion for me:

RegisterConditon('spell.charges', function(_, spell)
	local charges, maxCharges, start, duration = GetSpellCharges(spell)
	if duration then charges = charges + ( ( (GetTime()-start-(duration/10)) ) /10) end
	if charges == maxCharges then total = maxCharges end
	return charges
end)

and now if i have 1 charges and 50%cooldown for 2 charges i set in profile spell.charges <= 1.5 and they work.

**Comment by MrTheSoulz** [comment]
Thanks :)
