### ISSUE TITLE
Get number of units

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#64]
Request is based on LoD which heals in a cone in front of you but also a small circle around you.

So basically i need to get number of people around me 5 yards as well as people in front of me in a cone. 

Basically i should cast if there is 5 people in total in front and around me. 
So 1 in front and 4 around or 4 in front and 1 around. The issue i can see is that t could be double dipping with units in front and within around range.

**Comment by MrTheSoulz** [comment]
UNIT.area(DISTANCE).friendly gives you the number of friendly units around another unit.
Unit.healinfront(health, [num, maxDis]) for infront stuff (this may be tweaked to be UNIT.unitsinfront.enemie/friendly in the future).
Theres no cone yet

**Comment by MrTheSoulz** [comment]
Im not gonna add healcone in the core, it not possivel using only WoW's APIs.
It would require: `ObjectFacing(UNIT)` wich come from FH or EWT.
