### ISSUE TITLE
mouseover.gound w/ casttime redicle spells

### ISSUE THREAD

**Issue by aeonabyss** [MrTheSoulz/NerdPack#65]
Having an issue w/ mouseover.ground working with spells w/ casttime (warlock; rain of fire & cataclysm)

**Comment by MrTheSoulz** [comment]
I've tried:
`{'Flamestrike', 'keybind(shift)', 'mouseover.ground'}`

Seems to work correctly, will create a walock to try the exact same spells.

**Comment by MrTheSoulz** [comment]
'{'Cataclysm', 'keybind(shift)', 'mouseover.ground'},'
Also seems to work, closing this issue.
