### ISSUE TITLE
Comparison dont work

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#67]
After updating today there seems to be a problem with the parsing, or something else.

{'Holy Light','lowest.health =< 110', 'lowest'}, does not work
{'Holy Light', 'lowest'}, works

lowest.health is 100, tested with print.

**Comment by MrTheSoulz** [comment]
{'Holy Light', nil, 'lowest'},

**Comment by MrTheSoulz** [comment]
Like i said on discord, fakeunits are probably broken

**Comment by MrTheSoulz** [comment]
Should be fixed now
