### ISSUE TITLE
Interface buttons don't highlight when using ElvUI

### ISSUE THREAD

**Issue by modhunter** [MrTheSoulz/NerdPack#7]
When using ElvUI, the interface buttons don't properly 'highlight' (i.e. the colored border around the buttons) when they are enabled or disabled.  I remember this happened with probably engine as well.

I believe that the offending area is https://github.com/MrTheSoulz/NerdPack/blob/master/interface/mainframe.lua#L18-L24

Commenting-out this check results in non-elvui style buttons but the highlighting works properly.

IMHO highlighting is more valuable than ElvUI skinning, if this is a non-trivial fix.

**Comment by MrTheSoulz** [comment]
I had it working when i built it...
Wonder if something changed, will look into it soon

**Comment by MrTheSoulz** [comment]
Please verify if its fixef, thanks

**Comment by modhunter** [comment]
Fixed in https://github.com/MrTheSoulz/NerdPack/commit/ce03292986567116541612d28fac68bf4ff3774f

Thanks!
