### ISSUE TITLE
don't working debuff condition. "Virulent Plague" only

### ISSUE THREAD

**Issue by Kimbanjang** [MrTheSoulz/NerdPack#77]
in  016c774

Virulent Plague(191587) is main dot of DK Unholy.
This is spread when using Outbreak(77575).

So, I tried it.
`{ '77575', { 'target.debuff(191587)'.duration < 3 }, 'target' },`
but don't work condition. just repeat using Outbreak everytime.

retry it.
`{ '77575', { '!target.debuff(191587)' }, 'target' },`
same. I think return true to every condition.

I tested a different skill(ex. Moonfire of Druid). it's work fine.
Don't work Virulent Plague only. I tried to fix it, but didn't succeed.

PS. work fine same code at PE

**Comment by Kimbanjang** [comment]
```
{ '85948', { 'target.debuff(194310).count <= 5' }, 'target' }, -- Festering Strike
{ '77575', { '!lastcast(77575)', 'target.debuff(191587).duration < 10' }, 'target' }, -- Outbreak
```
work

```
{ '77575', { '!lastcast(77575)', 'target.debuff(191587).duration < 10' }, 'target' }, -- Outbreak
{ '85948', { 'target.debuff(194310).count <= 5' }, 'target' }, -- Festering Strike
```
don't work. i got pannic.

**Comment by MrTheSoulz** [comment]
Did you trie with names?
just to make sure theres nothing wrong with the ID

**Comment by MrTheSoulz** [comment]
should be fixed now
