### ISSUE TITLE
casting.percent wrong calculation

### ISSUE THREAD

**Issue by Weyoun** [MrTheSoulz/NerdPack#85]
As the title suggests, casting.percent is not calculating the percentage of time until completion (how much it is done) but rather the percentage of time gone by (how time is left). This might be intentional, but by the name of the function I would expect the prior behavior rather than the latter.

A minor adjustment will result in this behavior.

```
NeP.DSL:Register('casting.percent', function(target, spell)
	local name, startTime, endTime, notInterruptible = checkCasting(target)
	if name and not notInterruptible then
		local castLength = (endTime - startTime) / 1000
		local secondsDone = GetTime() - (startTime / 1000)
		return ((secondsDone/castLength)*100)
	end
	return 0
end)
```

**Comment by MrTheSoulz** [comment]
changed.
