### ISSUE TITLE
Healing is Broken

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#87]
Latest release broke healing. 

```
{'Holy Light', 'player.health < 95', 'player'},
{'Holy Light', 'lowest.health < 90', 'lowest'},
```
The selection of lowest is random and it is not the actual lowest in the party at all.
Doing Proven Grounds to test out and lowest always seems to be the same unit regardless if he is lowest or not.
Also /dump NeP.FakeUnits:Filter('lowest') dumps into target
Tested it olua and FH

**Comment by GabbzGit** [comment]
It seems that the lowest is "set" randomly and it will not change. Tested proven grounds and sometimes its party1 for the whole fight, sometimes its party3 etc.

So lowest is not dynamicaly updated but rather always the same.

**Comment by MrTheSoulz** [comment]
This should be fixed now.
