### ISSUE TITLE
Rotation doesn't execute on certain bosses such as Helya and Illysanna. Further, being at ranged, the rotation doesn't execute on Serpentrix and Wrath of Azshara (melee range works for those 2)

### ISSUE THREAD

**Issue by gypi** [MrTheSoulz/NerdPack#89]
Rotation doesn't execute on certain bosses such as Helya and Illysanna. Further, being at ranged, the rotation doesn't execute on Serpentrix and Wrath of Azshara (melee range works for those 2)

**Comment by Weyoun** [comment]
I am currently on commit 788e86e75ba363eeb696f58f1226dae938f6a2ec with some minor fixes for item usage and macros.
I cannot confirm this bug on this build.

**Comment by MrTheSoulz** [comment]
This Bug is due to LoS issues that only happen with advanced unlockers.

**Comment by zy4944796** [comment]
@MrTheSoulz  
I also found this problem .
What is the LoS issues?When I was fighting  against Nythendra the first Boss in Emerald Nightmare,the rotation suddenly stopped after a few minutes.
It's works fine with the other bosses.
Is the bug fixed today?

**Comment by MrTheSoulz** [comment]
Is this still valid? if so what unlocker are you using?

**Comment by tw88** [comment]
I am using FH, i had the same issue with Shadow Priest on Helyas Tentacles. But i think this could be because of Traceline checks failing...

**Comment by modhunter** [comment]
FYI, my [windwalker CR](https://github.com/modhunter/NerdPack-NoC/blob/master/rotations/monk/windwalker.lua) works fine against Helya's Tentacles using commit ed7fc5a

**Comment by jo32** [comment]
same issue on Helyas Tentacles.

**Comment by MrTheSoulz** [comment]
If tracelines fail on a certain boss please add it here and commit:
https://github.com/MrTheSoulz/NerdPack/blob/master/tables/bossids.lua#L36-L48

Or just add it on your addon.

NeP uses LiblossID to figure out if a certain unit is a boss and will bypass LoS checks on it, but the unit needs to be added to the list if not present.
