### ISSUE TITLE
Healing is Still broken

### ISSUE THREAD

**Issue by GabbzGit** [MrTheSoulz/NerdPack#92]
Updated to latest build and healing dont work still.

The error i get is
```
1x NerdPack\fakeunits.lua:14: attempt to compare two nil values
NerdPack\fakeunits.lua:14: in function <NerdPack\fakeunits.lua:14>
[C]: in function `sort'
NerdPack\fakeunits.lua:14: in function <NerdPack\fakeunits.lua:4>
(tail call): ?
NerdPack\system\parser.lua:34: in function `Target'
NerdPack\system\parser.lua:70: in function `Parse'
NerdPack\system\parser.lua:58: in function `Table'
NerdPack\system\parser.lua:68: in function `Parse'
NerdPack\system\parser.lua:100: in function <NerdPack\system\parser.lua:93>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
```

Testing some more it seems that prio is not set. And i dont want lowest to be based on prio regardless bit that is another topic.

There is something wrong with how the health is set since healthRaw have very strange value. In proven grounds the tank get 400% since he has a 25% damage reduction. Therefore he dont heal anyone since its  only when he gets into 15% he has a lower healthRaw then the rest.

**Comment by GabbzGit** [comment]
Please just add lowest that is based on currenthealth+incomingheals / Maxhealth

**Comment by GabbzGit** [comment]
line 10 in fakeunits.lua 
prio = prio should be Obj.prio = prio

**Comment by GabbzGit** [comment]
Healing.lua: NeP.Healing:Refresh dont cupdate the prio value so it is always set to initial value.

**Comment by GabbzGit** [comment]
When i add prio and only use health percentage all units get something like 400 except one unit Testing this in proven ground. 

Before combat the values seems fine but when we get into combat the rawhealth is just mulitpled with roughly 4. If i change the GetRawHealth to only use UnitHealth it still get x4.

**Comment by MrTheSoulz** [comment]
looking at healthRaw

**Comment by GabbzGit** [comment]
Changed around a bit
Some Q: 
FakeUnit lowest returns 
`return tempTable[num] and tempTable[num].key `
This is a changed from working where only the key was returned.

I changed the lowest unit code to 
```
NeP.FakeUnits:Add('lowest', function(num, role)
	local tempTable = {}
	
	for GUID, Obj in pairs(NeP.OM:Get('Friendly')) do
		if UnitPlayerOrPetInParty(Obj.key) or UnitIsUnit('player', Obj.key) then
			local healthRaw = NeP.Healing:GetRawHealth(Obj.key)
			local maxHealth = UnitHealthMax(Obj.key)
			local healthPercent =  (healthRaw / maxHealth) * 100
			tempTable[#tempTable+1] = {
				key = Obj.key,
				id = Obj.id,
				healthRaw = healthRaw,
				healthMax = maxHealth,
				health = healthPercent,
				distance = Obj.distance,
			}
		end
	end
	table.sort( tempTable, function(a,b) return a.health < b.health end )
	print("Unit :" ..tempTable[num].key .." Prio :" ..tempTable[num].health)
	return tempTable[num].key
	--return tempTable[num] and tempTable[num].key
end)
```

The print out is correct for me, ie the healt% of the unit. However the rotation is not casting altough it should and it starts casting when the lowest unit is at 20% when it should be casted at 95%

So i dont think that Nerdpack is using the values set here but something else somewhere

**Comment by GabbzGit** [comment]
Finally!!

The lowest only sort the units based on a value(prio which i changed to health)
But the check in the rotation is lowest.health
```
NeP.DSL:Register("health", function(target)
	local GUID = UnitGUID(target)
	local Obj = Roster[GUID]
	return Obj and Obj.health or ath.floor((UnitHealth(target) / UnitHealthMax(target)) * 100)
end)
```
```
When changing it to
NeP.DSL:Register("health", function(target)
	return math.floor((UnitHealth(target) / UnitHealthMax(target)) * 100
end)
```
I start healing!

**Comment by GabbzGit** [comment]
So basically using the roster to get the health is breaking the rotation

This code in fakeunits lowest works fine when using the OM to get the unit and health
```
NeP.FakeUnits:Add('lowest', function(nump, role)
	local tempTable = {}
	local num = nump or 1
	
	for GUID, Obj in pairs(NeP.OM:Get('Friendly')) do
		if UnitPlayerOrPetInParty(Obj.key) or UnitIsUnit('player', Obj.key) then
			local healthRaw = NeP.Healing:GetRawHealth(Obj.key)
			local maxHealth = UnitHealthMax(Obj.key)
			local healthPercent =  (healthRaw / maxHealth) * 100
			tempTable[#tempTable+1] = {
				key = Obj.key,
				id = Obj.id,
				healthRaw = healthRaw,
				healthMax = maxHealth,
				health = healthPercent,
				distance = Obj.distance,
			}
		end
	end
	table.sort( tempTable, function(a,b) return a.health < b.health end )
	print("Unit: " ..tempTable[num].key .." Health: " ..tempTable[num].health)
	return tempTable[num].key
	--return tempTable[num] and tempTable[num].key
end)
```
So prio is right and health is right when doing this
But when in the rotaiton using lowest.health is then producing the wrong health.

This does not work, it will heal only at 20% even if i set the lowest.health to 95
```
NeP.DSL:Register("health", function(target)
	local GUID = UnitGUID(target)
	local Obj = Roster[GUID]
	return Obj and Obj.health or math.floor((UnitHealth(target) / UnitHealthMax(target)) * 100)
end)
```
But if change it to
```
NeP.DSL:Register("health", function(target)
	return math.floor((UnitHealth(target) / UnitHealthMax(target)) * 100)
end)
```
then it works

**Comment by MrTheSoulz** [comment]
Ive done some changes that may fix this, please do let me know!

**Comment by MrTheSoulz** [comment]
This should no longer be an issue, closing.
