### ISSUE TITLE
area.enemies

### ISSUE THREAD

**Issue by gongmang1** [MrTheSoulz/NerdPack#95]
target.area(10).enemies > 2 can't work
EWT

**Comment by tw88** [comment]
it seems bugged for me too, i use something like {'aoespell', 'target.area(10).enemies > 2'},
and the aoe-spell is casted on singleTargets aswell...

**Comment by MrTheSoulz** [comment]
This this happening on dummies or real fights?

**Comment by gongmang1** [comment]
oh maybe is the EWT or NerdPack-Protected EWT.lua something wrong?

**Comment by gongmang1** [comment]
Message: [string "ok"]:358: attempt to perform arithmetic on local 'X2' (a nil value)
Time: 10/17/16 20:13:54
Count: 1
Stack: [C]: ?
[string "ok"]:358: in function <[string "ok"]:357>
(tail call): ?
(tail call): ?
Interface\AddOns\NerdPack\system\om.lua:30: in function `Filter'
Interface\AddOns\NerdPack\system\om.lua:36: in function `Insert'
Interface\AddOns\NerdPack\system\om.lua:55: in function `Add'
Interface\AddOns\NerdPack-Protected\firehack.lua:39: in function `Maker'
Interface\AddOns\NerdPack\system\om.lua:63: in function <Interface\AddOns\NerdPack\system\om.lua:62>
Interface\SharedXML\C_TimerAugment.lua:16: in function <Interface\SharedXML\C_TimerAugment.lua:14>

Locals:

**Comment by gongmang1** [comment]
oh maybe is the language
i put the NEP to enUS ,then no lua error

**Comment by MrTheSoulz** [comment]
Insteresting, checking...

**Comment by Biibou** [comment]
I have the same bug described by tw88, casting AoE spells on single target (using FH).
/reload ui didn't fixed it, I had to shutdown WoW.

An error also popped up when fighting a boss :

```
["message"] = "[string \"C:\\ToolZ\\FH\\Lua\\Object.lua\"]:18: The GUID does not belong to an existing object.",
["stack"] = "[C]: in function `ObjectPosition'
	[string \"C:\\ToolZ\\FH\\Lua\\Object.lua\"]:18: in function <[string \"C:\\ToolZ\\FH\\Lua\\Object.lua\"]:16>
	(tail call): ?\nInterface\\AddOns\\NerdPack\\system\\om.lua:30: in function `Filter'
	Interface\\AddOns\\NerdPack\\system\\om.lua:36: in function `Insert'
	Interface\\AddOns\\NerdPack\\system\\om.lua:56: in function `Add'
	Interface\\AddOns\\NerdPack-Protected\\firehack.lua:39: in function `Maker'
	Interface\\AddOns\\NerdPack\\system\\om.lua:64: in function <Interface\\AddOns\\NerdPack\\system\\om.lua:63>
	Interface\\SharedXML\\C_TimerAugment.lua:16: in function <Interface\\SharedXML\\C_TimerAugment.lua:14>",
```

**Comment by zy4944796** [comment]
@gongmang1  
My toon is Death Knight,and the AOE never executes.
I don't know why.
Any help?
Thank you .

**Comment by MrTheSoulz** [comment]
@Biibou that erros comes from an outdated version (1.5), ive pushed 1.6 to release so people using it are not affected.

**Comment by gongmang1** [comment]
@zy4944796   ,um,I delete the locale,only use enUS.
and then running well  
or,maybe the problem is the EWT?   If want to running well  ,you must Attach to WOW&lua unlock after login the role.

**Comment by Biibou** [comment]
@MrTheSoulz It was with the latest version, I git pull every commit (from master branch).
Maybe Im misaken, I'll let you know if it happens again.

**Comment by Biibou** [comment]
I confirm, latest version from git master branch and this error popup sometimes :

```
1x [string "C:\ToolZ\FH\Lua\Object.lua"]:18: The GUID does not belong to an existing object.
[C]: in function `ObjectPosition'
[string "C:\ToolZ\FH\Lua\Object.lua"]:18: in function <[string "C:\ToolZ\FH\Lua\Object.lua"]:16>
(tail call): ?
NerdPack\conditions\units.lua:330: in function <NerdPack\conditions\units.lua:326>
(tail call): ?
(tail call): ?
(tail call): ?
NerdPack\system\dsl.lua:119: in function <NerdPack\system\dsl.lua:114>
(tail call): ?
(tail call): ?
NerdPack\system\dsl.lua:61: in function <NerdPack\system\dsl.lua:57>
(tail call): ?
...
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
(tail call): ?
NerdPack\system\parser.lua:71: in function `Parse'
NerdPack\system\parser.lua:58: in function `Table'
NerdPack\system\parser.lua:67: in function `Parse'
NerdPack\system\parser.lua:99: in function <NerdPack\system\parser.lua:92>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:

```

**Comment by MrTheSoulz** [comment]
Sent a commit that may fix this, if so close this issue.

**Comment by Biibou** [comment]
Got this lua error another time today (in LFR) :
```
1x [string "C:\ToolZ\FH\Lua\Object.lua"]:18: The GUID does not belong to an existing object.
[C]: in function `ObjectPosition'
[string "C:\ToolZ\FH\Lua\Object.lua"]:18: in function <[string "C:\ToolZ\FH\Lua\Object.lua"]:16>
(tail call): ?
NerdPack\system\om.lua:30: in function `Filter'
NerdPack\system\om.lua:36: in function `Insert'
NerdPack\system\om.lua:56: in function `Add'
NerdPack-Protected\firehack.lua:39: in function `Maker'
NerdPack\system\om.lua:64: in function <NerdPack\system\om.lua:63>
SharedXML\C_TimerAugment.lua:16: in function <SharedXML\C_TimerAugment.lua:14>

Locals:
(*temporary) = "0x000001CACBC28444"
```

**Comment by gongmang1** [comment]
{'44457','target.area(20).enemies>1'},   still unavailable

zhCN, EWT

**Comment by gongmang1** [comment]
Use the code in the past

NeP.DSL:Register("area.enemies", function(unit, distance)
	local total = 0
	if not UnitExists(unit) then return total end
	for GUID, Obj in pairs(NeP.OM:Get('Enemy')) do
		if NeP.DSL:Get('combat')(Obj.key)
		and NeP.Protected.Distance(unit, Obj.key) <= tonumber(distance) then
			total = total +1
		end
	end
	return total
end)

zhCN client's area.enemies is available,but not the dummy

**Comment by MrTheSoulz** [comment]
@gongmang1 that is expected, the you need to add it to the locale/zhCH.
translate it from the enUS.
