### ISSUE TITLE
Item usage is broken

### ISSUE THREAD

**Issue by Biibou** [MrTheSoulz/NerdPack#97]
Item usage is currently broken in latest build.

{'#trinket1'},
{'#trinket2'},

The rotation is stuck, no lua error (using FH unlocker if it matters).

**Comment by Weyoun** [comment]
It's a bug in action.lua.
You could add `eval[1].spell = item` in line 34 for a fix until it's officially fixed.

**Comment by MrTheSoulz** [comment]
This as been fixed.
