### ISSUE TITLE
Does NerdPack 1.6 run well with EWT? 

### ISSUE THREAD

**Issue by zy4944796** [MrTheSoulz/NerdPack#98]
@MrTheSoulz  I download the NerdPack-1.6 just now ,then replaced the old version, but it did not run the combat routine.
I tested it in English client,it did not work yet.
Did I do something wrong?

![qq20161018203930](https://cloud.githubusercontent.com/assets/8578753/19478151/f62e3ff0-9573-11e6-9de0-61a8c8f36971.png)

**Comment by MrTheSoulz** [comment]
Did you update the protected nodule aswell?

**Comment by MrTheSoulz** [comment]
marking this as invalid until we know more.

**Comment by zy4944796** [comment]
@MrTheSoulz I downloaded the protected module today from https://github.com/MrTheSoulz/NerdPack-Protected,but it does not work any way.
Maybe I downloaded a wrong package.
Where can I download the latest version of protected module?

**Comment by gongmang1** [comment]
我已经搞好了……

**Comment by zy4944796** [comment]
@gongmang1 怎么搞好的.

**Comment by gongmang1** [comment]
@zy4944796 
用最新的NerdPack+ Xeer，EWT在登录进入游戏世界后注入并解锁，应该是没有问题的。

**Comment by zy4944796** [comment]
@gongmang1 依然不行,三个模块我下的最新的版本,也不行.可能我下载的链接不对?能告诉我你下载的链接吗.我用的是冰死骑

**Comment by zy4944796** [comment]
@gongmang1 我发现了,换成了圣骑,好像有效果,但是游戏死了.睡了,明天再研究.多谢你

**Comment by gongmang1** [comment]
@zy4944796 我试用的是火法，也是这三个模块最新版本，基本上是正常运行的，但是Protected中的castground在EWT下，仍需修改。area.enemies需要英文客户端支持…中文不可以呢…或者把该段函数替换成以前的，可用。
然后均可正常运行…
建议其他职业自己写一小段测试一下。或者打开actionlog寻找问题。
